#!/usr/bin/env python3
"""Populate the Heavy / Medium / Light Armor class sets from the armour dumps.

Reads armor/*.txt (tes3conv dumps), buckets every armour piece by its weight
class (the `Weight:... (Light|Medium|Heavy)` tag), and writes:

  * MWSE base set files   -> base-game (Morrowind+Tribunal+Bloodmoon) class rosters
  * add-on class blocks   -> TR/OAAB/NOD/AATL pieces added to the class sets
                             (a managed, re-generatable block per add-on main.lua)
  * OpenMW data.lua       -> the 3 class-set item arrays = base + all add-ons

Idempotent: re-run any time the dumps change. Shields are included (they carry a
weight class). Add-on ids are de-duplicated against base.

Usage:  python gen_class_sets.py
"""
import re, os, sys

ROOT  = os.path.dirname(os.path.abspath(__file__))
ARMOR = os.path.join(ROOT, "armor")

SOURCES = {
    "base": ["morrowind_armor_output.txt", "tribunal_armor_output.txt", "bloodmoon_armor_output.txt"],
    "TR":   ["TR_armor_output.txt", "tr_data_armor_output.txt"],
    "OAAB": ["oaab_armor_output.txt"],
    "NOD":  ["nod_armor_output.txt"],
    "AATL": ["aatl_armor_output.txt"],
}
CLASSES = ["Heavy", "Medium", "Light"]
SET_OF  = {"Heavy": "Heavy Armor", "Medium": "Medium Armor", "Light": "Light Armor"}
ADDONS  = [("SetBonusTR", "registerTRSets", "TR"),
           ("SetBonusOAAB", "registerOAAB", "OAAB"),
           ("SetBonusNOD", "registerNOD", "NOD"),
           ("SetBonusAATL", "registerAATL", "AATL")]

MARK_START = "    -- >>> SETBONUS CLASS ARMOR (auto-generated by gen_class_sets.py) >>>"
MARK_END   = "    -- <<< SETBONUS CLASS ARMOR <<<"


def parse(fname):
    path = os.path.join(ARMOR, fname)
    out, cur = [], None
    if not os.path.exists(path):
        return out
    for line in open(path, encoding="utf-8", errors="replace"):
        line = line.replace("\x00", "")
        m = re.match(r"\s*NAME: ID:(.+?)\s*$", line)
        if m:
            cur = m.group(1)
        m2 = re.search(r"AODT: Type:\(([^)]*)\).*?Weight:[\d.]+\s*\(([A-Za-z]+)\)", line)
        if m2 and cur is not None:
            out.append((cur.strip().lower(), m2.group(2)))
            cur = None
    return out


def roster(src):
    recs = []
    for fn in SOURCES[src]:
        recs += parse(fn)
    by, seen = {c: [] for c in CLASSES}, {c: set() for c in CLASSES}
    for _id, cls in recs:
        if cls in by and _id not in seen[cls]:
            seen[cls].add(_id); by[cls].append(_id)
    return by


def lua_items(ids, indent, per=4):
    if not ids:
        return indent + "-- (none)"
    rows = []
    for i in range(0, len(ids), per):
        rows.append(indent + ", ".join('"%s"' % x for x in ids[i:i + per]) + ",")
    return "\n".join(rows)


def read(p):
    return open(p, encoding="utf-8").read().replace("\x00", "")


def replace_items_block(text, newblock, start=0):
    """Replace the first `items = { ... }` (no nested braces) at/after `start`."""
    return re.sub(r"items\s*=\s*\{[^{}]*\}", newblock, text[start:], count=1)


def main():
    rosters = {s: roster(s) for s in SOURCES}
    base_ids = set()
    for c in CLASSES:
        base_ids |= set(rosters["base"][c])
    for s in SOURCES:
        if s == "base":
            continue
        for c in CLASSES:
            rosters[s][c] = [i for i in rosters[s][c] if i not in base_ids]

    summary = {}

    # 1. MWSE base set files (base-game rosters)
    for fname, cls in [("heavyarmor.lua", "Heavy"), ("mediumarmor.lua", "Medium"), ("lightarmor.lua", "Light")]:
        p = os.path.join(ROOT, "MWSE/mods/Static/ArmorBonus/sets", fname)
        s = read(p)
        block = "items = {\n" + lua_items(rosters["base"][cls], "\t\t") + "\n\t}"
        s = re.sub(r"items\s*=\s*\{[^{}]*\}", block, s, count=1)
        open(p, "w", encoding="utf-8").write(s)
        summary["base/" + cls] = len(rosters["base"][cls])

    # 2. add-on managed blocks
    for folder, funcname, src in ADDONS:
        lines = [MARK_START]
        for c in CLASSES:
            ids = rosters[src][c]
            if not ids:
                continue
            setname = SET_OF[c]
            lines += ['    if setBonus.getSet("%s") then' % setname,
                      '        setBonus.addItems("%s", {' % setname,
                      lua_items(ids, "            "),
                      "        })",
                      "    end"]
        lines.append(MARK_END)
        block = "\n".join(lines)
        p = os.path.join(ROOT, "MWSE/mods/Static", folder, "main.lua")
        s = read(p)
        if MARK_START in s:
            s = re.sub(re.escape(MARK_START) + r".*?" + re.escape(MARK_END), block, s, flags=re.S)
        else:
            anchor = "\nend\n\nevent.register(tes3.event.initialized, %s" % funcname
            if anchor not in s:
                sys.exit("ERROR: could not find injection anchor in %s/main.lua" % folder)
            s = s.replace(anchor, "\n" + block + "\nend\n\nevent.register(tes3.event.initialized, %s" % funcname, 1)
        open(p, "w", encoding="utf-8").write(s)
        summary[folder] = sum(len(rosters[src][c]) for c in CLASSES)

    # 3. OpenMW data.lua (base + all add-ons, per class)
    p = os.path.join(ROOT, "OpenMW_SetBonus/scripts/SetBonus/data.lua")
    s = read(p)
    for cls in CLASSES:
        allids = list(dict.fromkeys(rosters["base"][cls] + rosters["TR"][cls]
                      + rosters["OAAB"][cls] + rosters["NOD"][cls] + rosters["AATL"][cls]))
        block = "items = {\n" + lua_items(allids, "      ") + "\n    }"
        m = re.search(r'name\s*=\s*"' + re.escape(SET_OF[cls]) + r'"', s)
        if not m:
            sys.exit("ERROR: %s not found in OpenMW data.lua" % SET_OF[cls])
        s = s[:m.end()] + replace_items_block(s, block, m.end())
        summary["openmw/" + cls] = len(allids)
    open(p, "w", encoding="utf-8").write(s)

    print("Class-set population complete:")
    for k in sorted(summary):
        print("  %-16s %d" % (k, summary[k]))


if __name__ == "__main__":
    main()
