[package]
name = "Set Bonus"
description = "MWSE Set Bonus mod and framework: wear several pieces of an armour set to gain a scaling, lore-flavoured bonus."
homepage = "https://www.nexusmods.com/morrowind/mods/52911"
repository = "https://github.com/staticnation/set_bonus"
authors = ["StaticNation"]
version = "1.7.3"

[dependencies.mwse]
buildnumber = 3242

[tools.mwse]
lua-mod = "Static.SetBonus"
