return {
        name = "Heavy Armor",
        items = {
		"templar_pauldron_right", "templar boots", "templar bracer left", "templar bracer right",
      		"templar_pauldron_left", "templar_cuirass", "imperial left pauldron", "imperial right pauldron",
      		"imperial left gauntlet", "imperial right gauntlet", "imperial boots", "imperial helmet armor",
      		"imperial shield", "silver_helm", "silver_cuirass", "silver_dukesguard_cuirass",
      		"imperial_greaves", "nordic_iron_helm", "nordic_iron_cuirass", "templar_greaves",
      		"steel_helm", "steel_pauldron_left", "steel_pauldron_right", "steel_cuirass",
      		"steel_shield", "steel_towershield", "steel_gauntlet_left", "steel_gauntlet_right",
      		"steel_greaves", "iron_pauldron_left", "iron_pauldron_right", "iron_cuirass",
      		"iron_shield", "iron_towershield",
      		"iron_bracer_left", "iron_bracer_right", "iron_greaves", "trollbone_helm",
      		"trollbone_cuirass", "trollbone_shield", "dwemer_helm", "dwemer_pauldron_right",
      		"dwemer_pauldron_left", "dwemer_cuirass", "dwemer_bracer_left", "dwemer_bracer_right",
      		"dwemer_greaves", "dwemer_boots", "dwemer_shield", "ebony_closed_helm",
      		"ebony_pauldron_right", "ebony_pauldron_left", "ebony_cuirass", "ebony_bracer_left",
      		"ebony_bracer_right", "ebony_greaves", "ebony_boots", "ebony_shield",
      		"ebony_towershield", "daedric_fountain_helm", "daedric_terrifying_helm", "daedric_god_helm",
      		"daedric_pauldron_right", "daedric_pauldron_left", "daedric_cuirass", "daedric_gauntlet_left",
      		"daedric_gauntlet_right", "daedric_greaves", "daedric_boots", "daedric_shield",
      		"daedric_towershield", "templar_helmet_armor", "imperial cuirass_armor", "imperial_chain_pauldron_right",
      		"imperial_chain_pauldron_left", "iron_gauntlet_left", "iron_gauntlet_right", "iron_helmet",
      		"ebony_closed_helm_fghl", "blessed_shield", "holy_tower_shield", "helm of wounding",
      		"shield of wounds", "saint's shield", "azura's servant", "steel_boots",
      		"dwemer_boots of flying", "iron boots", "daedric_cuirass_htab", "daedric_greaves_htab",
      		"shadow_shield", "wraithguard", "wraithguard_jury_rig", "tenpaceboots",
      		"ebony_shield_auriel", "daedric_helm_clavicusvile", "ebony_bracer_left_tgeb", "ebony_bracer_right_tgeb",
     		"blessed_tower_shield", "lords_cuirass_unique", "spell_breaker_unique", "gauntlet_fists_l_unique",
      		"gauntlet_fists_r_unique", "towershield_eleidon_unique", "dragonbone_cuirass_unique", "helm_bearclaw_unique",
      		"imperial_helm_frald_uniq", "darksun_shield_unique", "bloodworm_helm_unique", "blood_feast_shield",
      		"imperial helmet armor_dae_curse", "towershield_eleidon_unique_x", "lords_cuirass_unique_x", "tenpaceboots_x",
      		"ebony_shield_auriel_x", "dragonbone_cuirass_unique_x", "helm_bearclaw_unique_x", "spell_breaker_unique_x",
      		"bloodworm_helm_unique_x", "ebony_cuirass_soscean", "silver_helm_uvenim", "indoril_almalexia_helmet",
      		"indoril_almalexia_boots", "indoril_almalexia_cuirass", "indoril_almalexia_greaves", "indoril_almalexia_pauldron_l",
      		"indoril_almalexia_pauldron_r", "indoril_almalexia_gauntlet_r", "indoril_almalexia_gauntlet_l", "indoril_almalexia_shield",
      		"dwemer_shield_battle_unique", "indoril_mh_guard_boots", "indoril_mh_guard_cuirass", "indoril_mh_guard_gauntlet_l",
      		"indoril_mh_guard_gauntlet_r", "indoril_mh_guard_greaves", "indoril_mh_guard_helmet", "indoril_mh_guard_pauldron_l",
      		"indoril_mh_guard_pauldron_r", "indoril_mh_guard_shield", "steel_boots_ancient", "steel_cuirass_ancient",
      		"steel_gauntlet_left_ancient", "steel_gauntlet_right_ancient", "steel_greaves_ancient", "steel_helm_ancient",
      		"steel_pauldron_left_ancient", "steel_pauldron_right_ancient", "steel_towershield_ancient", "bm_nordicmail_boots",
      		"bm_nordicmail_cuirass", "bm_nordicmail_pauldronl", "bm_nordicmail_pauldronr", "bm_nordicmail_gauntletl",
      		"bm_nordicmail_gauntletr", "bm_nordicmail_helmet", "bm_nordicmail_greaves", "bm_nordicmail_shield",
      		"t_bre_tourneyheater_shield_eec", "t_bre_tourneyheater_shield_fg", "t_bre_tourneyheater_shield_hdre", "t_bre_tourneyheater_shield_hhla",
      		"t_bre_tourneyheater_shield_hind", "t_bre_tourneyheater_shield_hred", "t_bre_tourneyheater_shield_htel", "t_bre_tourneyheater_shield_mas",
      		"t_bre_tourneyheater_shield_mg", "t_bre_tourneyheater_shield_oe", "t_bre_uni_lordlyheatershield", "t_bre_uni_trickstershield",
      		"t_bre_woodenheater_shield_01", "t_bre_woodenheater_shield_02", "t_bre_woodenheater_shield_03", "t_bre_woodenheater_shield_04",
      		"t_bre_woodenheater_shield_05", "t_bre_woodenheater_shield_06", "t_bre_woodenheater_shield_07", "t_bre_woodenheater_shield_08",
      		"t_bre_woodenheater_shield_09", "t_bre_woodenheater_shield_10", "t_bre_woodenheater_shield_11", "t_bre_woodenheater_shield_12",
      		"t_bre_woodenheater_shield_13", "t_bre_woodenheater_shield_14", "t_bre_woodenheater_shield_15", "t_bre_woodenheater_shield_glyph",
      		"t_bre_woodenheater_shield_gn", "t_bre_woodenheater_shield_rose", "t_com_ironskull_pauldronl_01", "t_com_ironskull_pauldronr_01",
      		"t_com_ironspike_helm_01", "t_com_ironspike_helm_shield", "t_com_ironspike_pauldronl_01", "t_com_ironspike_pauldronr_01",
      		"t_com_iron_boots_01", "t_com_iron_boots_02", "t_com_iron_boots_shield", "t_com_iron_bracerl_01",
      		"t_com_iron_bracerl_02", "t_com_iron_bracerl_blunt", "t_com_iron_bracerr_01", "t_com_iron_bracerr_02",
      		"t_com_iron_bracerr_blunt", "t_com_iron_cuirass_01", "t_com_iron_cuirass_02", "t_com_iron_cuirass_strength",
      		"t_com_iron_gauntletl_axe", "t_com_iron_gauntletr_axe", "t_com_iron_greaves_01", "t_com_iron_greaves_02",
      		"t_com_iron_helm_01", "t_com_iron_helm_02", "t_com_iron_helm_03", "t_com_iron_helm_04",
      		"t_com_iron_helm_open", "t_com_iron_helm_open_02", "t_com_iron_pauldronl_01", "t_com_iron_pauldronl_02",
      		"t_com_iron_pauldronr_01", "t_com_iron_pauldronr_02", "t_com_iron_shield_fire", "t_com_steelspike_pauldronl_01",
      		"t_com_steelspike_pauldronr_01", "t_com_steel_boots_consuming", "t_com_steel_boots_creeping", "t_com_steel_boots_glacial",
      		"t_com_steel_boots_perfection", "t_com_steel_boots_shield", "t_com_steel_cuirass_01", "t_com_steel_cuirass_02",
      		"t_com_steel_cuirass_03", "t_com_steel_cuirass_04", "t_com_steel_cuirass_crusader", "t_com_steel_cuirass_duskdawn",
      		"t_com_steel_cuirass_finalvirtue", "t_com_steel_cuirass_outermost", "t_com_steel_cuirass_scalypelt", "t_com_steel_cuirass_steelhearth",
      		"t_com_steel_gauntletl_rainfire", "t_com_steel_gauntletl_scathing", "t_com_steel_gauntletl_summer", "t_com_steel_gauntletl_wonder",
      		"t_com_steel_gauntletr_rainfire", "t_com_steel_gauntletr_scathing", "t_com_steel_gauntletr_summer", "t_com_steel_gauntletr_wonder",
      		"t_com_steel_greaves_bitingpains", "t_com_steel_greaves_kings", "t_com_steel_greaves_stamptoad", "t_com_steel_greaves_unrequited",
      		"t_com_steel_helm_01", "t_com_steel_helm_despair", "t_com_steel_helm_open_01", "t_com_steel_helm_open_02",
      		"t_com_steel_helm_preciptious", "t_com_steel_helm_tonguewyrm", "t_com_steel_helm_turnundead", "t_com_steel_helm_windingroad",
      		"t_com_steel_pauldronl_01", "t_com_steel_pauldronl_02", "t_com_steel_pauldronl_03", "t_com_steel_pauldronl_mishand",
      		"t_com_steel_pauldronl_monkeyapp", "t_com_steel_pauldronl_sacred", "t_com_steel_pauldronl_winterwin", "t_com_steel_pauldronr_01",
      		"t_com_steel_pauldronr_02", "t_com_steel_pauldronr_03", "t_com_steel_pauldronr_mishand", "t_com_steel_pauldronr_monkeyapp",
      		"t_com_steel_pauldronr_sacred", "t_com_steel_pauldronr_winterwin", "t_com_steel_shield_silence", "t_com_steel_tshield_scamp",
      		"t_com_uni_handofglory_helnim", "t_com_uni_requiem", "t_cr_goblin_helm_01", "t_cr_goblin_pauldronl_01",
      		"t_cr_goblin_pauldronr_01", "t_dae_alternate2_boots_01", "t_dae_alternate2_cuirass_01", "t_dae_alternate2_gauntletl_01",
      		"t_dae_alternate2_gauntletr_01", "t_dae_alternate2_greaves_01", "t_dae_alternate2_helmopen_01", "t_dae_alternate2_helm_01",
      		"t_dae_alternate2_pauldronl_01", "t_dae_alternate2_pauldronr_01", "t_dae_alternate_boots_01", "t_dae_alternate_buckler_01",
      		"t_dae_alternate_cuirass_01", "t_dae_alternate_gauntletl_01", "t_dae_alternate_gauntletr_01", "t_dae_alternate_greaves_01",
      		"t_dae_alternate_helmopen_01", "t_dae_alternate_helm_01", "t_dae_alternate_pauldronl_01", "t_dae_alternate_pauldronr_01",
      		"t_dae_lord_boots_01", "t_dae_lord_gauntletl_01", "t_dae_lord_gauntletr_01", "t_dae_lord_helm_01",
      		"t_dae_lord_pauldronl_01", "t_dae_lord_pauldronr_01", "t_dae_regular_helmaberration_01", "t_dae_regular_helmconsolat_01",
      		"t_dae_regular_helmhumiliat_01", "t_dae_regular_helmhumiliat_02", "t_dae_regular_helmrebellion_01", "t_dae_regular_helmrenewal_01",
      		"t_dae_regular_pauldronl_01", "t_dae_regular_pauldronr_01", "t_dae_regular_shieldtower_01", "t_dae_uni_bootsofpeace_01",
      		"t_dae_uni_fearstruck", "t_dae_uni_helmlightwithin_01", "t_dae_uni_lmethatspauldron", "t_dae_uni_rmethatspauldron",
      		"t_de_almarula_helm_uni", "t_de_ebony_helmopen_01", "t_de_ebony_helm_02", "t_de_hvchit_boots",
      		"t_de_hvchit_cuirass", "t_de_hvchit_gauntlet_l", "t_de_hvchit_gauntlet_r", "t_de_hvchit_greaves",
      		"t_de_hvchit_helmet", "t_de_hvchit_pauldron_l", "t_de_hvchit_pauldron_r", "t_de_uni_eboncres_narsis",
      		"t_de_uni_ebonycuirass_pasoroth", "t_de_uni_pasoroth_boots",
      		"t_de_uni_pasoroth_cuirass", "t_de_uni_pasoroth_gaunt_l", "t_de_uni_pasoroth_gaunt_r", "t_de_uni_pasoroth_greaves",
      		"t_de_uni_pasoroth_helm", "t_de_uni_pasoroth_pauld_l", "t_de_uni_pasoroth_pauld_r", "t_de_uni_shield_abernanit",
      		"t_de_uni_veloth_pauld_l", "t_de_uni_veloth_pauld_r", "t_dwe_gold_boots", "t_dwe_gold_cuirass",
      		"t_dwe_gold_gauntlet_l", "t_dwe_gold_gauntlet_r", "t_dwe_gold_greaves", "t_dwe_gold_helm",
      		"t_dwe_gold_pauldron_l", "t_dwe_gold_pauldron_r", "t_dwe_regular_cuirass_lightning", "t_dwe_regular_shieldtower_01",
      		"t_dwe_rourken_boots_01", "t_dwe_rourken_bracer_l_01", "t_dwe_rourken_bracer_r_01", "t_dwe_rourken_cuirass_01",
      		"t_dwe_rourken_greaves_01", "t_dwe_rourken_helm_01", "t_dwe_rourken_pauld_l_01", "t_dwe_rourken_pauld_r_01",
      		"t_dwe_uni_maskofpurity", "t_he_steel_shield_01", "t_imp_alessianbrnz_boots_01", "t_imp_alessianbrnz_cuirass_01",
      		"t_imp_alessianbrnz_gauntletl_01", "t_imp_alessianbrnz_gauntletr_01", "t_imp_alessianbrnz_helm_01", "t_imp_alessianbrnz_pauldronl_01",
      		"t_imp_alessianbrnz_pauldronr_01", "t_imp_alessianbrnz_tshield_01", "t_imp_coliron1_boots_01", "t_imp_coliron1_boots_02",
      		"t_imp_coliron1_boots_03", "t_imp_coliron1_boots_04", "t_imp_coliron1_cuirass_01", "t_imp_coliron1_cuirass_02",
      		"t_imp_coliron1_cuirass_03", "t_imp_coliron1_cuirass_04", "t_imp_coliron1_gauntletl_01", "t_imp_coliron1_gauntletl_02",
      		"t_imp_coliron1_gauntletl_03", "t_imp_coliron1_gauntletl_04", "t_imp_coliron1_gauntletr_01", "t_imp_coliron1_gauntletr_02",
      		"t_imp_coliron1_gauntletr_03", "t_imp_coliron1_gauntletr_04", "t_imp_coliron1_greaves_01", "t_imp_coliron1_greaves_02",
      		"t_imp_coliron1_greaves_03", "t_imp_coliron1_greaves_04", "t_imp_coliron1_helm_01", "t_imp_coliron1_helm_02",
      		"t_imp_coliron1_helm_03", "t_imp_coliron1_helm_04", "t_imp_coliron1_pauldronl_01", "t_imp_coliron1_pauldronl_02",
      		"t_imp_coliron1_pauldronl_03", "t_imp_coliron1_pauldronl_04", "t_imp_coliron1_pauldronr_01", "t_imp_coliron1_pauldronr_02",
      		"t_imp_coliron1_pauldronr_03", "t_imp_coliron1_pauldronr_04", "t_imp_coliron_boots_01", "t_imp_coliron_bracerl_01",
      		"t_imp_coliron_bracerr_01", "t_imp_coliron_cuirass_01", "t_imp_coliron_greaves_01", "t_imp_coliron_helmet_01",
      		"t_imp_coliron_helmet_02", "t_imp_coliron_pauldronl_01", "t_imp_coliron_pauldronr_01", "t_imp_colsteel1_boots_01",
      		"t_imp_colsteel1_boots_02", "t_imp_colsteel1_boots_03", "t_imp_colsteel1_boots_04", "t_imp_colsteel1_bracerl_01",
      		"t_imp_colsteel1_bracerl_02", "t_imp_colsteel1_bracerl_03", "t_imp_colsteel1_bracerl_04", "t_imp_colsteel1_bracerr_01",
      		"t_imp_colsteel1_bracerr_02", "t_imp_colsteel1_bracerr_03", "t_imp_colsteel1_bracerr_04", "t_imp_colsteel1_cuirass_01",
      		"t_imp_colsteel1_cuirass_02", "t_imp_colsteel1_cuirass_03", "t_imp_colsteel1_cuirass_04", "t_imp_colsteel1_greaves_01",
      		"t_imp_colsteel1_greaves_02", "t_imp_colsteel1_greaves_03", "t_imp_colsteel1_greaves_04", "t_imp_colsteel1_helm_01",
      		"t_imp_colsteel1_helm_02", "t_imp_colsteel1_helm_03", "t_imp_colsteel1_helm_04", "t_imp_colsteel1_pauldronl_01",
      		"t_imp_colsteel1_pauldronl_02", "t_imp_colsteel1_pauldronl_03", "t_imp_colsteel1_pauldronl_04", "t_imp_colsteel1_pauldronr_01",
      		"t_imp_colsteel1_pauldronr_02", "t_imp_colsteel1_pauldronr_03", "t_imp_colsteel1_pauldronr_04", "t_imp_colsteel_boots_01",
      		"t_imp_colsteel_boots_02", "t_imp_colsteel_boots_03", "t_imp_colsteel_boots_04", "t_imp_colsteel_bracerl_03",
      		"t_imp_colsteel_bracerl_04", "t_imp_colsteel_bracerr_03", "t_imp_colsteel_bracerr_04", "t_imp_colsteel_cuirass_01",
      		"t_imp_colsteel_cuirass_02", "t_imp_colsteel_cuirass_03", "t_imp_colsteel_cuirass_04", "t_imp_colsteel_gauntletl_01",
      		"t_imp_colsteel_gauntletl_02", "t_imp_colsteel_gauntletr_01", "t_imp_colsteel_gauntletr_02", "t_imp_colsteel_greaves_01",
      		"t_imp_colsteel_greaves_02", "t_imp_colsteel_greaves_03", "t_imp_colsteel_greaves_04", "t_imp_colsteel_helm_01",
      		"t_imp_colsteel_helm_02", "t_imp_colsteel_helm_03", "t_imp_colsteel_helm_04", "t_imp_colsteel_helm_05",
      		"t_imp_colsteel_helm_06", "t_imp_colsteel_pauldronl_01", "t_imp_colsteel_pauldronl_02", "t_imp_colsteel_pauldronl_03",
      		"t_imp_colsteel_pauldronl_04", "t_imp_colsteel_pauldronr_01", "t_imp_colsteel_pauldronr_02", "t_imp_colsteel_pauldronr_03",
      		"t_imp_colsteel_pauldronr_04", "t_imp_ebony_boots", "t_imp_ebony_bracerl", "t_imp_ebony_bracerr",
      		"t_imp_ebony_cuirass", "t_imp_ebony_helmet_01", "t_imp_ebony_helmet_02", "t_imp_ebony_helmet_02b",
      		"t_imp_ebony_helmet_03", "t_imp_ebony_helmet_03b", "t_imp_ebony_pauldronl", "t_imp_ebony_pauldronr",
      		"t_imp_ebony_shieldtower_01", "t_imp_gold_boots_02", "t_imp_gold_bracerl_02", "t_imp_gold_bracerr_02",
      		"t_imp_gold_cuirass_02", "t_imp_gold_gauntletl_02", "t_imp_gold_gauntletr_02", "t_imp_gold_greaves_02",
      		"t_imp_gold_helm_02", "t_imp_gold_pauldronl_02", "t_imp_gold_pauldronr_02", "t_imp_gold_shield_01",
      		"t_imp_guardtown1_boots_01", "t_imp_guardtown1_helmanv_01", "t_imp_guardtown1_helmstr_01", "t_imp_guardtown1_helmsut_01",
      		"t_imp_guardtown1_helm_01", "t_imp_guardtown2_helmart_01", "t_imp_guardtown2_helmbru_01", "t_imp_guardtown2_helmcho_01",
      		"t_imp_guardtown2_helm_01", "t_imp_guardtown3_boots_01", "t_imp_guardtown3_gauntletl_01", "t_imp_guardtown3_gauntletr_01",
      		"t_imp_guardtown3_greaves_01", "t_imp_guardtown3_helmkva_01", "t_imp_guardtown3_helmsar_01", "t_imp_guardtown3_helmskn_01",
      		"t_imp_guardtown3_helm_01", "t_imp_militia_boots_01", "t_imp_militia_greaves_01", "t_imp_militia_helm_01",
      		"t_imp_militia_pauldronl_01", "t_imp_militia_pauldronr_01", "t_imp_mothherder_helmet_01", "t_imp_navyoff_boots_01",
      		"t_imp_navyoff_bracerl_01", "t_imp_navyoff_bracerr_01", "t_imp_navyoff_cuirass_01", "t_imp_navyoff_greaves_01",
      		"t_imp_navyoff_helmet_01", "t_imp_navyoff_pauldronl_01", "t_imp_navyoff_pauldronr_01", "t_imp_nibbronze_boots_01",
      		"t_imp_nibbronze_bracerl_01", "t_imp_nibbronze_bracerr_01", "t_imp_nibbronze_cuirass_01", "t_imp_nibbronze_greaves_01",
      		"t_imp_nibbronze_helm_01", "t_imp_nibbronze_pauldronl_01", "t_imp_nibbronze_pauldronr_01", "t_imp_rddmtmp_boots_01",
      		"t_imp_rddmtmp_bracerl_01", "t_imp_rddmtmp_bracerr_01", "t_imp_rddmtmp_cuirass_01", "t_imp_rddmtmp_greaves_01",
      		"t_imp_rddmtmp_helmet_01", "t_imp_rddmtmp_pauldronl_01", "t_imp_rddmtmp_pauldronr_01", "t_imp_rddmtmp_shield_01",
      		"t_imp_silver_boots_01", "t_imp_silver_bracerl_01", "t_imp_silver_bracerr_01", "t_imp_silver_cap_01",
      		"t_imp_silver_cap_02", "t_imp_silver_cuirassfw_01", "t_imp_silver_cuirassred_01", "t_imp_silver_greaves_01",
      		"t_imp_silver_helm_mask", "t_imp_silver_pauldronl_01", "t_imp_silver_pauldronr_01", "t_imp_steel_helm_health",
      		"t_imp_templar_shieldtower_01", "t_imp_uni_blacksmithshandl", "t_imp_uni_blacksmithshandr", "t_imp_uni_bracerl_bifurication",
      		"t_imp_uni_bracerr_bifurication", "t_imp_uni_dragoneye", "t_imp_uni_evergaurd", "t_imp_uni_urielshield_01",
      		"t_imp_uni_queennagheacuir", "t_imp_wood_shieldtower_01", "t_kha_copper_shield_01", "t_nor_ancient_boots_01",
      		"t_nor_ancient_bracerl_01", "t_nor_ancient_bracerr_01", "t_nor_ancient_cuirass_01", "t_nor_ancient_greaves_01",
      		"t_nor_ancient_helm_01", "t_nor_ancient_helm_02", "t_nor_ancient_helm_03", "t_nor_ancient_pauldronl_01",
      		"t_nor_ancient_pauldronl_02", "t_nor_ancient_pauldronr_01", "t_nor_ancient_pauldronr_02", "t_nor_ancient_shield",
      		"t_nor_ancient_shield_01", "t_nor_companion_helm_01", "t_nor_iron_boots_01", "t_nor_iron_boots_leap",
      		"t_nor_iron_cuirass_wintery", "t_nor_iron_gauntletl_01", "t_nor_iron_gauntletr_01", "t_nor_iron_greaves_01",
      		"t_nor_iron_helm_resistfrost", "t_nor_iron_pauldronl_01", "t_nor_iron_pauldronr_01", "t_nor_rearoy_boots_01",
      		"t_nor_rearoy_bracerl_01", "t_nor_rearoy_bracerr_01", "t_nor_rearoy_cuirass_01", "t_nor_rearoy_helm_01",
      		"t_nor_rearoy_pauldronl_01", "t_nor_rearoy_pauldronr_01", "t_nor_steel_boots_01", "t_nor_steel_cuirass_01",
      		"t_nor_steel_cuirass_steelhearth", "t_nor_steel_gauntletl_01", "t_nor_steel_gauntletr_01", "t_nor_steel_greaves_01",
      		"t_nor_steel_helm_01", "t_nor_steel_pauldronl_01", "t_nor_steel_pauldronr_01", "t_nor_trollbone_boots_01",
      		"t_nor_trollbone_bracerl_01", "t_nor_trollbone_bracerr_01", "t_nor_trollbone_greaves_01", "t_nor_trollbone_greaves_vigor",
      		"t_nor_trollbone_pauldronl_01", "t_nor_trollbone_pauldronr_01", "t_nor_uni_kvisahjaelmur", "t_nor_uni_targeblooded",
      		"t_qyk_chitin_boots_01", "t_qyk_chitin_cuirass_01", "t_qyk_chitin_gauntletl_01", "t_qyk_chitin_gauntletr_01",
      		"t_qyk_chitin_greaves_01", "t_qyk_chitin_helmet_01", "t_qyk_chitin_pauldronl_01", "t_qyk_chitin_pauldronr_01",
      		"t_rga_ironlamellar_boots_01", "t_rga_ironlamellar_bracer_l_01", "t_rga_ironlamellar_bracer_r_01", "t_rga_ironlamellar_cuirass_01",
      		"t_rga_ironlamellar_greaves_01", "t_rga_ironlamellar_helm_01", "t_rga_ironlamellar_pauld_l_01", "t_rga_ironlamellar_pauld_r_01",
      		"t_rga_iron_boots_01", "t_rga_iron_boots_02", "t_rga_iron_bracerl_01", "t_rga_iron_bracerl_02",
      		"t_rga_iron_bracerr_01", "t_rga_iron_bracerr_02", "t_rga_iron_cuirass_01", "t_rga_iron_cuirass_02",
      		"t_rga_iron_greaves_01", "t_rga_iron_greaves_02", "t_rga_iron_helm_01", "t_rga_iron_helm_02",
      		"t_rga_iron_pauldronl_01", "t_rga_iron_pauldronl_02", "t_rga_iron_pauldronr_01", "t_rga_iron_pauldronr_02",
      		"t_rga_steel_boots_01", "t_rga_steel_cuirass_01", "t_rga_steel_gauntletl_01", "t_rga_steel_gauntletr_01",
      		"t_rga_steel_greaves_01", "t_rga_steel_helm_01", "t_rga_steel_pauldronl_01", "t_rga_steel_pauldronr_01",
      		"ab_a_daeazurahelm", "ab_a_daedagonhelm", "ab_a_daemolaghelm", "ab_a_daesheoghelm",
      		"ab_a_ebonyhelmopen", "ab_a_impbmboots", "ab_a_impbmcuirass", "ab_a_impbmgreaves",
      		"ab_a_impbmhelm", "ab_a_impbmpldleft", "ab_a_impbmpldright", "ab_a_invisshield",
      		"ab_a_irondeboots", "ab_a_irondecuirass", "ab_a_irondehelm", "ab_a_irondehelmtong",
      		"ab_a_irondepldleft", "ab_a_irondepldright", "ab_a_steelhelmopen", "nod_dnk_qor_cuirass",
      		"nod_dnk_qor_p_left", "nod_dnk_qor_p_right", "nod_dnk_mandas_cuirass", "nod_dnk_mandas_p_left",
      		"nod_dnk_mandas_p_right", "nod_dnk_duke_cuirass", "nod_dnk_seanwen_cuirass", "nod_dnk_seanwen_p_left",
      		"nod_dnk_seanwen_p_right", "nod_dnk_duke_p_left", "nod_dnk_duke_p_right", "nod_dnk_dwem_boots",
      		"nod_dnk_dwem_cuirass", "nod_dnk_dwem_grv", "nod_dnk_dwem_l_gaunt", "nod_dnk_dwem_l_pauldron",
      		"nod_dnk_dwem_mask", "nod_dnk_dwem_r_gaunt", "nod_dnk_dwem_r_pauldron", "nod_arimpbattlemage",
      		"nod_ar_legionbm", "nod_rv_duke's_helmet", "nod_rv_duke's_greaves", "nod_rv_duke's_boots",
      		"nod_rv_duke's_pauld_r", "nod_rv_duke's_pauld_l", "nod_rv_duke's_gauntlet_r", "nod_rv_duke's_gauntlet_l",
      		"nod_rv_daedric_helm_dagon", "nod_rv_daedric_helm_molag", "nod_rv_daedric_helm_sheo", "nod_rv_hc_cuirass",
      		"nod_rv_hc_greaves", "nod_rv_hc_helmet", "nod_rv_hc_boots", "nod_rv_hc_pauldron - left",
      		"nod_rv_hc_pauldron - right", "nod_rv_hc_guantlet - left", "nod_rv_hc_guantlet - right", "nod_hat_mabrigash_ah_buglord",
      		"nod_hat_iron_rm_headwear_07", "nod_hat_iron_rm_headwear_08", "nod_hat_iron_rm_headwear_09", "aatl_art_visage_mzund",
	},
	bonuses = {
		min = {
			{ effect = "resistNormalWeapons", magnitude = 3 },
			{ effect = "fortifyHealth", magnitude = 8 },
		},
		mid = {
			{ effect = "resistNormalWeapons", magnitude = 5 },
			{ effect = "fortifyHealth", magnitude = 12 },
			{ effect = "fortifyAttribute", attribute = "endurance", magnitude = 5 },
		},
		max = {
			{ effect = "resistNormalWeapons", magnitude = 8 },
			{ effect = "fortifyHealth", magnitude = 18 },
			{ effect = "fortifyAttribute", attribute = "endurance", magnitude = 8 },
		},
	},
}
