return {
        name = "Light Armor",
        items = {
		"chitin cuirass", "chitin pauldron - left", "chitin pauldron - right", "chitin boots",
      		"chitin greaves", "chitin helm", "chitin guantlet - left", "chitin guantlet - right",
      		"right leather bracer", "left leather bracer", "cloth bracer left", "cloth bracer right",
      		"netch_leather_helm", "netch_leather_boiled_helm", "netch_leather_pauldron_left", "netch_leather_cuirass",
      		"netch_leather_boiled_cuirass", "netch_leather_gauntlet_left", "netch_leather_gauntlet_right", "netch_leather_greaves",
      		"netch_leather_boots", "netch_leather_shield", "netch_leather_towershield", "fur_helm",
      		"fur_colovian_helm", "fur_pauldron_left", "fur_cuirass", "fur_bearskin_cuirass",
      		"fur_bracer_left", "fur_bracer_right", "fur_greaves", "fur_boots",
      		"nordic_leather_shield", "dust_adept_helm", "mole_crab_helm", "cephalopod_helm",
      		"imperial_studded_cuirass", "chitin_mask_helm", "chitin_watchman_helm", "chitin_shield",
      		"chitin_towershield", "newtscale_cuirass", "morag_tong_helm", "glass_helm",
      		"glass_cuirass", "glass_shield", "glass_towershield", "netch_leather_pauldron_right",
      		"fur_pauldron_right", "fur_gauntlet_left", "fur_gauntlet_right", "glass_pauldron_left",
      		"glass_pauldron_right", "merisan_cuirass", "shield_of_light", "the_chiding_cuirass",
      		"velothian_helm", "feather_shield", "velothis_shield", "veloths_tower_shield",
      		"demon helm", "demon mole crab", "demon cephalopod", "right horny fist gauntlet",
      		"left_horny_fist_gauntlet", "right gauntlet of horny fist", "left gauntlet of the horny fist", "velothian shield",
      		"merisan helm", "chest of fire", "bound_cuirass", "bound_helm",
      		"bound_boots", "bound_shield", "fiend helm", "devil helm",
      		"devil mole crab helm", "devil cephalopod helm", "right cloth horny fist bracer", "left cloth horny fist bracer",
      		"heavy_leather_boots", "glass_boots", "glass_greaves", "bound_gauntlet_right",
      		"bound_gauntlet_left", "boots of blinding speed[unique]", "veloths_shield", "gauntlet_horny_fist_r",
      		"gauntlet _horny_fist_l", "cuirass_savior_unique", "boots_apostle_unique", "shield of the undaunted",
      		"conoon_chodala_boots_unique", "icecap_unique", "boneweave gauntlet", "bonedancer gauntlet",
      		"cephalopod_helm_htnk", "gauntlet_of_glory_left", "gauntlet_of_glory_right", "glass_bracer_left",
      		"glass_bracer_right", "cuirass_savior_unique_x", "boots_apostle_unique_x", "boots of blinding speed_x",
      		"darkbrotherhood helm", "darkbrotherhood cuirass", "darkbrotherhood greaves", "darkbrotherhood pauldron_l",
      		"darkbrotherhood pauldron_r", "darkbrotherhood gauntlet_l", "darkbrotherhood gauntlet_r", "darkbrotherhood boots",
      		"goblin_shield", "goblin_shield_durgok_uni", "bm wolf cuirass", "bm wolf greaves",
      		"bm wolf helmet", "bm wolf left gauntlet", "bm wolf left pauldron", "bm wolf right gauntlet",
      		"bm wolf right pauldron", "bm wolf boots", "fur_colovian_helm_red", "fur_colovian_helm_white",
      		"bm_ice minion_shield1", "bm_wolf_cuirass_snow", "bm_wolf_greaves_snow", "bm_wolf_helmet_snow",
      		"bm_wolf_left_gauntlet_snow", "bm_wolf_left_pauldron_snow", "bm_wolf_right_gauntlet_snow", "bm_wolf_right_pauldron_snow",
      		"bm_wolf_boots_snow", "bm wolf shield", "bm wolf helmet_heartfang", "wolfwalkers",
      		"t_ayl_saliache_boots_01", "t_ayl_saliache_bracerl_01", "t_ayl_saliache_bracerr_01", "t_ayl_saliache_cuirass_01",
      		"t_ayl_saliache_greaves_01", "t_ayl_saliache_helm_01", "t_ayl_saliache_pauldronl_01", "t_ayl_saliache_pauldronr_01",
      		"t_ayl_saliache_shield_01", "t_bre_bjoulsaefur_helm_01", "t_bre_cm_hatchef_01", "t_bre_cm_hat_01a",
      		"t_bre_cm_hat_01b", "t_bre_cm_hat_02", "t_bre_cm_hat_03", "t_bre_cm_hat_04a",
      		"t_bre_cm_hat_04b", "t_bre_cm_hat_04c", "t_bre_cm_hat_05a", "t_bre_cm_hat_05b",
      		"t_bre_cm_hat_06", "t_bre_ep_hatost_01", "t_bre_ep_hatwizard_01", "t_bre_ep_hatwizard_02",
      		"t_bre_ep_hat_01", "t_bre_ep_hat_02", "t_bre_ep_hat_03", "t_bre_ep_hat_04",
      		"t_bre_ep_hat_05", "t_bre_ep_hat_06a", "t_bre_ep_hat_06b", "t_bre_ep_hat_07",
      		"t_bre_ep_hat_08a", "t_bre_ep_hat_08b", "t_bre_et_boots_01", "t_bre_et_boots_02",
      		"t_bre_et_hat_01", "t_bre_et_hat_02", "t_bre_et_hat_03", "t_bre_ex_hat_01",
      		"t_bre_ex_hat_02", "t_com_bound_greaves_01", "t_com_bound_pauldronl_01", "t_com_bound_pauldronr_01",
      		"t_com_chitin_gauntletl_restor", "t_com_chitin_gauntletr_restor", "t_com_cloth_bracerl_shortblade", "t_com_cloth_bracerr_shortblade",
      		"t_com_cm_hatclothcoif_01", "t_com_cm_hatclothcoif_02", "t_com_cm_hat_01", "t_com_cm_hat_02",
      		"t_com_cm_hat_03", "t_com_cm_hat_04", "t_com_cm_hat_05", "t_com_cm_hat_06",
      		"t_com_cm_hat_haggling", "t_com_eq_hat_01", "t_com_et_hatclothcoif_01", "t_com_et_hat_01",
      		"t_com_et_hat_02", "t_com_et_hat_03", "t_com_et_hat_04", "t_com_et_hat_05",
      		"t_com_et_hat_foresight", "t_com_et_hat_imperious", "t_com_foolshat_01", "t_com_foolshat_02",
      		"t_com_netch_helm_nighteye", "t_cr_goblin_shield_01", "t_dae_uni_aurorangauntletl", "t_dae_uni_aurorangauntletr",
      		"t_dae_uni_bootssaviorshide", "t_dae_uni_gauntletofpoor_l", "t_dae_uni_gauntletofpoor_r", "t_dae_uni_greavessaviorshide",
      		"t_dae_uni_helmsaviorshide", "t_dae_uni_lgauntsaviorshide", "t_dae_uni_lpauldsaviorshide", "t_dae_uni_rgauntsaviorshide",
      		"t_dae_uni_rpauldsaviorshide", "t_de_alithide_boots_01", "t_de_alithide_bracerl_01", "t_de_alithide_bracerl_poison",
      		"t_de_alithide_bracerr_01", "t_de_alithide_bracerr_poison", "t_de_alithide_cuirass_01", "t_de_alithide_greaves_01",
      		"t_de_alithide_helmopen_01", "t_de_alithide_helm_01", "t_de_alithide_pauldronl_01", "t_de_alithide_pauldronr_01",
      		"t_de_alithide_shield_01", "t_de_alithide_shield_fatigue", "t_de_alithide_towershield_01", "t_de_ashl_scout_helm",
      		"t_de_caravaner_helm_01", "t_de_chitin_boots_speed", "t_de_chitin_helmopen_01", "t_de_chitin_pauldrl_01",
      		"t_de_chitin_pauldrr_01", "t_de_chitin_pioneerhelm_01", "t_de_chitin_pioneerhelm_02", "t_de_chitin_tshield_health",
      		"t_de_cm_hattelv_01", "t_de_cm_hattelv_02", "t_de_cm_hattelv_03", "t_de_cm_hattelv_04",
      		"t_de_cm_hattelv_05", "t_de_daedrichide_boots_01", "t_de_daedrichide_cuirass_01", "t_de_daedrichide_gauntletl_01",
      		"t_de_daedrichide_gauntletr_01", "t_de_daedrichide_greaves_01", "t_de_daedrichide_pauldronl_01", "t_de_daedrichide_pauldronr_01",
      		"t_de_diviner_helm_01", "t_de_dreschapthil_helm_01a", "t_de_dreschapthil_helm_01b", "t_de_dreschapthil_helm_01c",
      		"t_de_dreschapthil_helm_01d", "t_de_dreschapthil_helm_01e", "t_de_dreschapthil_helm_02a", "t_de_dreschapthil_helm_02b",
      		"t_de_dreschapthil_helm_02c", "t_de_dreschapthil_helm_02d", "t_de_dreschapthil_helm_02e", "t_de_dreschapthil_helm_03a",
      		"t_de_dreschapthil_helm_03b", "t_de_dreschapthil_helm_03c", "t_de_dreschapthil_helm_03d", "t_de_dreschapthil_helm_03e",
      		"t_de_dreshunter_cuirass_01", "t_de_dreshunter_greaves_01", "t_de_dreshunter_helm_01", "t_de_dreshunter_pauldronl_01",
      		"t_de_dreshunter_pauldronr_01", "t_de_dressaltmerc_helm_01", "t_de_dressaltmerc_helm_02", "t_de_ep_hattelv_01",
      		"t_de_ep_hattelv_02", "t_de_ep_hattelv_03", "t_de_et_hattelv_01", "t_de_et_hattelv_02",
      		"t_de_ex_hattelv_01", "t_de_ex_hattelv_02", "t_de_fiendcephalopodhelm_01", "t_de_fiendmolecrabhelm_01",
      		"t_de_glassgilded_boots_01", "t_de_glassgilded_bracerl_01", "t_de_glassgilded_bracerr_01", "t_de_glassgilded_cuirass_01",
      		"t_de_glassgilded_greaves_01", "t_de_glassgilded_helm_01", "t_de_glassgilded_pauldronl_01", "t_de_glassgilded_pauldronr_01",
      		"t_de_glass_helm_closed_01", "t_de_indchevaram_boots_01", "t_de_indchevaram_bracerl_01", "t_de_indchevaram_bracerr_01",
      		"t_de_indchevaram_cuirass_01", "t_de_indchevaram_greaves_01", "t_de_indchevaram_helm_01", "t_de_indchevaram_helm_02",
      		"t_de_indchevaram_pauldrl_01", "t_de_indchevaram_pauldrr_01", "t_de_kagoutihide_boots_01", "t_de_kagoutihide_bracerl_01",
      		"t_de_kagoutihide_bracerr_01", "t_de_kagoutihide_cuirass_01", "t_de_kagoutihide_cuirass_hunter", "t_de_kagoutihide_greaves_01",
      		"t_de_kagoutihide_helmopen_01", "t_de_kagoutihide_helm_01", "t_de_kagoutihide_helm_hunter", "t_de_kagoutihide_pauldronl_01",
      		"t_de_kagoutihide_pauldronr_01", "t_de_kagoutihide_shield_01", "t_de_kagoutihide_shield_02", "t_de_kagoutihide_shield_sanct",
      		"t_de_kagoutihide_tshield_tusks", "t_de_kagoutihide_towershield_01", "t_de_molecrab_boots_01", "t_de_molecrab_boots_feather",
      		"t_de_molecrab_boots_slowfall", "t_de_molecrab_bracerl_01", "t_de_molecrab_bracerl_conj", "t_de_molecrab_bracerl_dest",
      		"t_de_molecrab_bracerl_illusion", "t_de_molecrab_bracerr_01", "t_de_molecrab_bracerr_conj", "t_de_molecrab_bracerr_dest",
      		"t_de_molecrab_bracerr_illusion", "t_de_molecrab_cuirass_01", "t_de_molecrab_cuirass_absorp", "t_de_molecrab_greaves_01",
      		"t_de_molecrab_pauldronl_01", "t_de_molecrab_pauldronr_01", "t_de_moragtong_boots_01", "t_de_moragtong_bracerl_01",
      		"t_de_moragtong_bracerr_01", "t_de_moragtong_cuirass_01", "t_de_moragtong_greaves_01", "t_de_moragtong_pauldronl_01",
      		"t_de_moragtong_pauldronr_01", "t_de_netchrogue_cuirass_01", "t_de_netchrogue_helm_01", "t_de_netchrogue_helm_02",
      		"t_de_netchrogue_helm_key", "t_de_netchstalker_helm_01", "t_de_netch_boots_speed", "t_de_netch_cuirass_01",
      		"t_de_netch_cuirass_02", "t_de_netch_cuirass_03", "t_de_netch_gauntletl_marksman", "t_de_netch_gauntletr_marksman",
      		"t_de_netch_helm_01", "t_de_netch_helm_02", "t_de_redwatchchitin_boots_01", "t_de_redwatchchitin_cuirass_01",
      		"t_de_redwatchchitin_gauntll_01", "t_de_redwatchchitin_gauntlr_01", "t_de_redwatchchitin_greaves_01", "t_de_redwatchchitin_pauldrl_01",
      		"t_de_redwatchchitin_pauldrr_01", "t_de_redoranwatchman_boots", "t_de_redoranwatchman_boots_fati", "t_de_redoranwatchman_cuirass",
      		"t_de_redoranwatchman_gauntletl", "t_de_redoranwatchman_gauntletr", "t_de_redoranwatchman_greaves", "t_de_redoranwatchman_helm_det",
      		"t_de_redoranwatchman_pauldronl", "t_de_redoranwatchman_pauldronr", "t_de_shinchitin_boots", "t_de_shinchitin_bracerl",
      		"t_de_shinchitin_bracerr", "t_de_shinchitin_cuirass", "t_de_shinchitin_greaves", "t_de_shinchitin_helm",
      		"t_de_shinchitin_pauldl", "t_de_shinchitin_pauldr", "t_de_telvcephalopod_boots_01", "t_de_telvcephalopod_boots_burd",
      		"t_de_telvcephalopod_boots_lev", "t_de_telvcephalopod_cuirass_01", "t_de_telvcephalopod_gauntl_01", "t_de_telvcephalopod_gauntl_alt",
      		"t_de_telvcephalopod_gauntl_mys", "t_de_telvcephalopod_gauntr_01", "t_de_telvcephalopod_gauntr_alt", "t_de_telvcephalopod_gauntr_mys",
      		"t_de_telvcephalopod_greaves_01", "t_de_telvcephalopod_pauldl_01", "t_de_telvcephalopod_pauldr_01", "t_de_telvcephalopod_reflect",
      		"t_de_uni_kagoutihide_bracerl_01", "t_de_uni_kagoutihide_bracerr_01", "t_de_uni_kingofrats_01", "t_de_uni_preyseekerhelm",
      		"t_de_uni_ushudimmucrown", "t_de_uni_vizard_draloris", "t_glb_var_headfixer", "t_he_altmerglass_boots_01",
      		"t_he_altmerglass_cuirass_01", "t_he_altmerglass_greaves_01", "t_he_altmerglass_helm_01", "t_he_altmerglass_helm_02",
      		"t_he_altmerglass_helm_03", "t_he_altmerglass_l_bracer_01", "t_he_altmerglass_l_pauldron_01", "t_he_altmerglass_r_bracer_01",
      		"t_he_altmerglass_r_pauldron_01", "t_he_direnni_boots_01", "t_he_direnni_bracerl_01", "t_he_direnni_bracerr_01",
      		"t_he_direnni_cuirass_01", "t_he_direnni_greaves_01", "t_he_direnni_helm_01", "t_he_direnni_pauldronl_01",
      		"t_he_direnni_pauldronr_01", "t_he_glass_towershield_01", "t_imp_cm_bootscol_01", "t_imp_cm_bootscol_02",
      		"t_imp_cm_bootscol_03", "t_imp_cm_bootscol_04", "t_imp_cm_hatcolwest_01", "t_imp_cm_hatcolwest_02",
      		"t_imp_colfur_boots_01", "t_imp_colfur_boots_02", "t_imp_colfur_boots_03", "t_imp_colfur_boots_04",
      		"t_imp_colfur_cuirass_01", "t_imp_colfur_cuirass_02", "t_imp_colfur_cuirass_03", "t_imp_colfur_cuirass_04",
      		"t_imp_colfur_gauntl_01", "t_imp_colfur_gauntl_02", "t_imp_colfur_gauntl_03", "t_imp_colfur_gauntl_04",
      		"t_imp_colfur_gauntr_01", "t_imp_colfur_gauntr_02", "t_imp_colfur_gauntr_03", "t_imp_colfur_gauntr_04",
      		"t_imp_colfur_helmbl_01", "t_imp_colfur_helmex_01", "t_imp_colfur_helmr_01", "t_imp_colfur_helmtiger_01",
      		"t_imp_colgoathide_boots_01", "t_imp_colgoathide_greaves_01", "t_imp_colgoathide_helmet_01", "t_imp_colleather_boots_01",
      		"t_imp_colleather_boots_02", "t_imp_colleather_bracerl_01", "t_imp_colleather_bracerl_02", "t_imp_colleather_bracerr_01",
      		"t_imp_colleather_bracerr_02", "t_imp_colleather_cuirass_01", "t_imp_colleather_cuirass_02", "t_imp_colleather_greaves_01",
      		"t_imp_colleather_greaves_02", "t_imp_colleather_helm_01", "t_imp_colleather_helm_02", "t_imp_colleather_pauldronl_01",
      		"t_imp_colleather_pauldronl_02", "t_imp_colleather_pauldronr_01", "t_imp_colleather_pauldronr_02", "t_imp_domina_boots_01",
      		"t_imp_domina_cuirass_01", "t_imp_domina_gauntletl_01", "t_imp_domina_gauntletr_01", "t_imp_domina_greaves_01",
      		"t_imp_domina_helm_01", "t_imp_domina_pauldronl_01", "t_imp_domina_pauldronr_01", "t_imp_ebonweave_boots_01",
      		"t_imp_ebonweave_bracerl_01", "t_imp_ebonweave_bracerr_01", "t_imp_ebonweave_cuirass_01", "t_imp_ebonweave_greaves_01",
      		"t_imp_ebonweave_helm_01", "t_imp_ebonweave_helm_02", "t_imp_ebonweave_pauldronl_01", "t_imp_ebonweave_pauldronr_01",
      		"t_imp_ep_hatcolwest_01", "t_imp_ep_hatcolwest_02", "t_imp_ep_hatcolwest_03", "t_imp_ep_hatcolwest_04",
      		"t_imp_ep_hat_02", "t_imp_et_hatcolnorth_01", "t_imp_et_hatcolnorth_02", "t_imp_et_hatcolnorth_03",
      		"t_imp_et_hatcolnorth_04", "t_imp_et_hatcolnorth_05", "t_imp_navystud_boots_01", "t_imp_navystud_cuirass_01",
      		"t_imp_navystud_gauntletl_01", "t_imp_navystud_gauntletr_01", "t_imp_navystud_helm_01", "t_imp_navystud_pauldrl_01",
      		"t_imp_navystud_pauldrr_01", "t_imp_newtscale_boots_01", "t_imp_newtscale_cuirass_01", "t_imp_newtscale_gauntletl_01",
      		"t_imp_newtscale_gauntletr_01", "t_imp_newtscale_greaves_01", "t_imp_newtscale_helm_01", "t_imp_newtscale_pauldronl_01",
      		"t_imp_newtscale_pauldronr_01", "t_imp_studdedleather_boots_01", "t_imp_studdedleather_bracerl_01", "t_imp_studdedleather_bracerr_01",
      		"t_imp_studdedleather_greaves_01", "t_imp_studdedleather_helm_01", "t_imp_studdedleather_helm_02", "t_imp_studdedleather_helm_03",
      		"t_imp_studdedleather_pauldrl_01", "t_imp_studdedleather_pauldrr_01", "t_imp_studdedleather_cuirass_02", "t_imp_studdedleather_cuirass_03",
      		"t_imp_uni_katariahsdeathmask", "t_imp_uni_masquedcaptain", "t_imp_uni_shadowweave", "t_nor_bearskin_boots_01",
      		"t_nor_bearskin_bracerl_01", "t_nor_bearskin_bracerl_claw", "t_nor_bearskin_bracerr_01", "t_nor_bearskin_bracerr_claw",
      		"t_nor_bearskin_greaves_01", "t_nor_bearskin_helm_01", "t_nor_bearskin_helm_hiber", "t_nor_bearskin_pauldronl_01",
      		"t_nor_bearskin_pauldronr_01", "t_nor_haafscpol_boots_01", "t_nor_haafscpol_helm_01", "t_nor_hornedleather_helm_01",
      		"t_nor_leather1_barcerl_01", "t_nor_leather1_barcerr_01", "t_nor_leather1_boots_01", "t_nor_leather1_cuirass_01",
      		"t_nor_leather1_greaves_01", "t_nor_leather1_helm_01", "t_nor_leather1_pauldl_01", "t_nor_leather1_pauldr_01",
      		"t_nor_leather2_boots_01", "t_nor_leather2_bracerl_01", "t_nor_leather2_bracerr_01", "t_nor_leather2_cuirass_01",
      		"t_nor_leather2_greaves_01", "t_nor_leather2_helm_01", "t_nor_leather2_pauldl_01", "t_nor_leather2_pauldr_01",
      		"t_nor_unihornedleather_helm", "t_nor_uni_predatorsgrace", "t_nor_wolf_helm_black_01", "t_nor_wolf_helm_red_01",
      		"t_nor_wolf_helm_white_01", "t_nor_wood_shieldbuckler_01", "t_nor_wood_shieldbuckler_02", "t_nor_wood_shieldbuckler_03",
      		"t_nor_wood_shieldbuckler_04", "t_nor_wood_shieldbuckler_05", "t_nor_wood_shieldbuckler_06", "t_nor_wood_shieldbuckler_07",
      		"t_nor_wood_shieldbuckler_08", "t_orc_leather_boots_01", "t_orc_leather_cuirass_01", "t_orc_leather_gauntletl_01",
      		"t_orc_leather_gauntletr_01", "t_orc_leather_greaves_01", "t_orc_leather_helm_01", "t_orc_leather_pauldronl_01",
      		"t_orc_leather_pauldronr_01", "t_qyk_manatee_boots_01", "t_qyk_manatee_bracerl_01", "t_qyk_manatee_bracerr_01",
      		"t_qyk_manatee_cuirass_01", "t_qyk_manatee_greaves_01", "t_qyk_manatee_helm_01", "t_qyk_manatee_pauldronl_01",
      		"t_qyk_manatee_pauldronr_01", "t_qy_ngalom_bracerl_uni", "t_qy_ngalom_bracerr_uni", "t_rea_leather_hat_01",
      		"t_rea_leather_hat_witchery", "t_rea_uni_feathercrown", "t_rga_cm_hat_01", "t_rga_cm_hat_02",
      		"t_rga_cm_hat_03", "t_rga_ep_headdress_01", "t_rga_guardrihad_boots_01", "t_rga_guardrihad_bracer_l_01",
      		"t_rga_guardrihad_bracer_r_01", "t_rga_guardrihad_cuirass_01", "t_rga_guardrihad_helm_01", "t_rga_guardrihad_pauldron_l_01",
      		"t_rga_guardrihad_pauldron_r_01", "t_rga_lamellar_bracer_l_01", "t_rga_lamellar_bracer_r_01", "t_rga_lamellar_cuirass",
      		"t_rga_lamellar_cuirass_b", "t_rga_lamellar_cuirass_g", "t_rga_lamellar_cuirass_y", "t_rga_lamellar_helm",
      		"t_rga_lamellar_helm_b", "t_rga_lamellar_helm_g", "t_rga_lamellar_helm_y", "t_rga_wicker_shield",
      		"t_cr_goblin_helm_01", "t_cr_goblin_pauldronl_01", "t_cr_goblin_pauldronr_01", "ab_a_backbasket",
      		"ab_a_bonemlightboots", "ab_a_bonemlightbracerl", "ab_a_bonemlightbracerr", "ab_a_bonemlightcuirass",
      		"ab_a_bonemlightgreaves", "ab_a_bonemlighthelm", "ab_a_bonemlightpaull", "ab_a_bonemlightpaulr",
      		"ab_a_bugblueboots", "ab_a_bugbluecuirass", "ab_a_bugbluegntleft", "ab_a_bugbluegntright",
      		"ab_a_bugbluegreaves", "ab_a_bugbluehelm", "ab_a_bugbluepldleft", "ab_a_bugbluepldright",
      		"ab_a_bugblueshield", "ab_a_buggreenboots", "ab_a_buggreencuirass", "ab_a_buggreengntleft",
      		"ab_a_buggreengntright", "ab_a_buggreengreaves", "ab_a_buggreenhelm", "ab_a_buggreenpldleft",
      		"ab_a_buggreenpldright", "ab_a_buggreenshield", "ab_a_cephhelmopen", "ab_a_cephpauldronleft",
      		"ab_a_cephpauldronright", "ab_a_chitinhelmopen", "ab_a_chitinhlahelm01", "ab_a_chitinredhelm01",
      		"ab_a_chitinscouthelm", "ab_a_chitintelhelm01", "ab_a_clothhelm1", "ab_a_clothhelm2",
      		"ab_a_clothhelm3", "ab_a_dustboots", "ab_a_dustbracerleft", "ab_a_dustbracerright",
      		"ab_a_dustchest", "ab_a_dustgreaves", "ab_a_dusthelm", "ab_a_dustpldrleft",
      		"ab_a_dustpldrright", "ab_a_eggminerhelm", "ab_a_glassassassinpauldronleft", "ab_a_glassassassinpauldronright",
      		"ab_a_glasshelmclose", "ab_a_leatherhat", "ab_a_moragtonghelm01", "ab_a_moragtonghelm02",
      		"ab_a_moragtonghelm03", "ab_a_moragtonghelm04", "ab_a_netchboilpldleft", "ab_a_netchboilpldright",
      		"ab_a_netchimancap", "ab_a_wickerhelm", "ab_a_wickerhelm02", "ab_c_commonhood01",
      		"ab_c_commonhood02", "ab_c_commonhood02h", "ab_c_commonhood02hh", "ab_c_commonhood02r",
      		"ab_c_commonhood02rr", "ab_c_commonhood02t", "ab_c_commonhood02tt", "ab_c_commonhood03",
      		"ab_c_commonhood03a", "ab_c_commonhood03b", "ab_c_commonhood04", "ab_c_commonhood05",
      		"ab_c_commonhood05a", "ab_c_commonhood05b", "ab_c_commonhood05c", "ab_c_commonhoodblack",
      		"ab_c_dwrvhat", "ab_c_expensivehood01", "ab_c_expensivehood02", "ab_c_expensivehood02a",
      		"ab_c_expensivehood03", "ab_c_exquisitehood01", "ab_c_extravaganthood01", "ab_c_extravaganthood01a",
      		"ab_c_extravaganthood01b", "ab_c_extravaganthood01c", "ab_c_extravaganthood01h", "ab_c_extravaganthood01r",
      		"ab_c_extravaganthood01t", "ab_c_extravaganthood02", "nod_hat_turban04_war_kha_br", "nod_hat_turban04_war_kha_w",
      		"nod_hat_turban04_war_kha_x_br", "nod_hat_turban04_war_kha_wx", "nod_hat_war_kha_mask01", "nod_hat_war_kha_mask02",
      		"nod_war_misc_backpack01a", "nod_war_misc_backpack02a", "nod_war_misc_pouch01", "nod_war_misc_pouch04",
      		"nod_dnk_missun_cuirass", "nod_dnk_eno_cuirass", "nod_rv_chitin helm d_hr", "nod_rv_chitin helm e_ht",
      		"nod_rv_chitin helm f_hh", "nod_hat_netch_rv_netchimans cap", "nod_1ba_pauldron_right", "nod_1ba_pauldron_left",
      		"nod_1ba_guantlet_right", "nod_1ba_bracer_left", "nod_1ba_greaves", "nod_1ba_cuirass",
      		"nod_1ba_boots", "nod_1ba_cuirass02", "nod_1ba_helm", "nod_1ba_hood_",
      		"nod_1ba_scarf_g", "nod_arimpofficial", "nod_arnightblade", "nod_mabrigash_ar01",
      		"nod_mabrigash_ar02", "nod_mabrigash_ar04", "nod_mabrigash_ar03", "nod_admscarfred",
      		"nod_admscarforange", "nod_admscarfyellow", "nod_admscarfgreen", "nod_admscarfblue",
      		"nod_admscarfdeepblue", "nod_admscarfpurple", "nod_admscarfrose", "nod_admscarfgrey",
      		"nod_admscarfblack", "nod_kd_femgdia", "nod_kd_femgem", "nod_kd_femgru",
      		"nod_kd_femgsa", "nod_kd_femssa", "nod_kd_femsdia", "nod_kd_femsem",
      		"nod_kd_femsru", "nod_earrings_01", "nod_earrings_02", "nod_earrings_03",
      		"nod_earrings_03a", "nod_!aoi_veil_black", "nod_!aoi_veil_blue", "nod_!aoi_veil_green",
      		"nod_!aoi_veil_lavender", "nod_!aoi_veil_olive", "nod_!aoi_veil_pink", "nod_kd_bandcopper",
      		"nod_kd_bandgold", "nod_kd_bandmithril", "nod_kd_bandorc", "nod_kd_chainblack",
      		"nod_kd_chainblackgems", "nod_kd_chaingold", "nod_kd_chainsilver", "nod_kd_chainsilvergems",
      		"nod_kd_chaingoldgems", "nod_kd_circletbblue", "nod_kd_circletbgreen", "nod_kd_circletbpearl",
      		"nod_kd_circletbred", "nod_kd_circletbtopaz", "nod_kd_circletgtopaz", "nod_kd_circletgblue",
      		"nod_kd_circletggreen", "nod_kd_circletgpearl", "nod_kd_circletgred", "nod_kd_circletstopaz",
      		"nod_kd_circletsred", "nod_kd_circletspearl", "nod_kd_circletsgreen", "nod_kd_circletsblue",
      		"nod_kd_diag", "nod_kd_dias", "nod_kd_diagdia", "nod_kd_elvdia",
      		"nod_kd_elvem", "nod_kd_elvru", "nod_kd_twin", "nod_kd_twins",
      		"nod_kd_diagem", "nod_kd_diagru", "nod_kd_diagsa", "nod_kd_diasdia",
      		"nod_kd_diasem", "nod_kd_diasru", "nod_kd_diassa", "nod_!aoi_scarf_black",
      		"nod_!aoi_scarf_blue", "nod_!aoi_scarf_green", "nod_!aoi_scarf_purple", "nod_!aoi_scarf_red",
      		"nod_!aoi_scarf_silver", "nod_!aoi_scarf_teal", "nod_!aoi_scarf_yellow", "nod_kd_g01",
      		"nod_kd_g02", "nod_kd_g03", "nod_kd_g04", "nod_kd_g05",
      		"nod_kd_g06", "nod_kd_g01r", "nod_kd_g06r", "nod_kd_g05r",
      		"nod_kd_g04r", "nod_kd_g03r", "nod_kd_g02r", "nod_kd_s06r",
      		"nod_kd_s06", "nod_kd_s05r", "nod_kd_s05", "nod_kd_s04r",
      		"nod_kd_s04", "nod_kd_s03r", "nod_kd_s03", "nod_kd_s02r",
      		"nod_kd_s02", "nod_kd_s01r", "nod_kd_s01", "nod_!aoi_01black1",
      		"nod_!aoi_01black2", "nod_!aoi_01brown1", "nod_!aoi_01brown2", "nod_!aoi_01red1",
      		"nod_!aoi_01red2", "nod_!aoi_02black1", "nod_!aoi_02black2", "nod_!aoi_02black3",
      		"nod_!aoi_02brown1", "nod_!aoi_02brown2", "nod_!aoi_02brown3", "nod_!aoi_02red1",
      		"nod_!aoi_02white3", "nod_!aoi_03black1", "nod_!aoi_03black1s", "nod_!aoi_03brown1",
      		"nod_!aoi_03red1", "nod_!aoi_03white1", "nod_!aoi_20black1", "nod_!aoi_20black1s",
      		"nod_!aoi_20brown2", "nod_!aoi_20red1s", "nod_!aoi_20white1", "nod_!aoi_21black1",
      		"nod_!aoi_21black1s", "nod_!aoi_21brown1", "nod_!aoi_21brown2", "nod_!aoi_21white1",
      		"nod_!aoi_22black1", "nod_!aoi_22red1", "nod_!aoi_23black2", "nod_!aoi_23black2s",
      		"nod_!aoi_23red1", "nod_!aoi_11black1", "nod_!aoi_11black1s", "nod_!aoi_11brown1",
      		"nod_!aoi_11red1s", "nod_!aoi_11brown1s", "nod_!aoi_11white1", "nod_!aoi_17black",
      		"nod_!aoi_17blacks", "nod_!aoi_17brown", "nod_!aoi_17browns", "nod_!aoi_17reds",
      		"nod_!aoi_17white", "nod_!aoi_12black1", "nod_!aoi_12black1s", "nod_!aoi_12black2",
      		"nod_!aoi_12brown1", "nod_!aoi_12brown2", "nod_!aoi_12red2", "nod_!aoi_12white2",
      		"nod_!aoi_24red1", "nod_!aoi_24black2", "nod_!aoi_24black3", "nod_!aoi_24black4",
      		"nod_!aoi_24brown1", "nod_!aoi_24brown2", "nod_!aoi_24brown3", "nod_!aoi_24red4",
      		"nod_!aoi_24white1", "nod_!aoi_13black1", "nod_!aoi_13black1s", "nod_!aoi_13brown1",
      		"nod_!aoi_13brown1s", "nod_!aoi_13red1", "nod_!aoi_13white1", "nod_!aoi_14black",
      		"nod_!aoi_14blacks", "nod_!aoi_14browns", "nod_!aoi_14reds", "nod_!aoi_14white",
      		"nod_!aoi_16black", "nod_!aoi_16blacks", "nod_!aoi_16brown", "nod_!aoi_16red",
      		"nod_!aoi_16whites", "nod_!aoi_15black", "nod_!aoi_15blacks", "nod_!aoi_15brown",
      		"nod_!aoi_15browns", "nod_!aoi_15red", "nod_!aoi_15white", "nod_!aoi_31black1",
      		"nod_!aoi_31black2", "nod_!aoi_31red2s", "nod_!aoi_31black3", "nod_!aoi_31brown1",
      		"nod_!aoi_31white2", "nod_!aoi_31brown3", "nod_!aoi_31brown3s", "nod_!aoi_31red1",
      		"nod_!aoi_31white2s", "nod_!aoi_35black", "nod_!aoi_35brown", "nod_!aoi_35red",
      		"nod_!aoi_35white", "nod_!aoi_23white2", "nod_!aoi_23brown2s", "nod_rv_sacred_necro_boots",
      		"nod_rv_sacred_necro_cuirass", "nod_rv_sacred_necro_bracer_l", "nod_rv_sacred_necro_bracer_r", "nod_rv_sacred_necro_greaves",
      		"nod_rv_sacred_necro_hood", "nod_rv_sacred_necro_pauld_l", "nod_rv_sacred_necro_pauld_r", "nod_rv_necromask",
      		"nod_rv_archnecromask", "nod_rv_necroboots", "nod_rv_necrohood", "nod_rv_archnecrohood",
      		"nod_retex_6th_robe1", "nod_retex_6th_ar_lbcuirass2", "ak_cloth_helm_uni", "nod_hat_ash_ah_dustmask",
      		"nod_hat_ash_r0_gogglehood_w", "nod_hat_mabrigash_r0_mask", "nod_hat_shroomcap_emperor", "nod_hat_shroomcap_b",
      		"nod_hat_shroomcap_br", "nod_hat_shroomcap_w", "nod_hat_bug_g", "nod_hat_shroomcap_telvanni",
      		"nod_hat_shroomcowl", "nod_hat_turban01_rm", "nod_hat_turban02_rm", "nod_hat_turban03_rm",
      		"nod_hat_crab_rm_mcrabhelm01", "nod_hat_crab_rm_mcrabhelm02", "nod_hat_crab_rm_mcrabhelm03", "nod_rm_mcrabshield01",
      		"nod_rm_mcrabshield02", "nod_rm_mcrabshield03", "nod_hat_iron_rm_headwear04", "nod_hat_iron_rm_headwear05",
      		"nod_hat_iron_rm_headwear06", "nod_hat_straw_rm_wickerhelmet01", "nod_hat_straw_rm_wickerhelmet02", "nod_hat_straw_rm_wickerhelmet03",
      		"nod_rm_wickershield01", "nod_rm_wickershield02", "nod_rm_wickershield03", "nod_hat_telv_rm_headwear_10",
      		"nod_hat_telv_rm_headwear_11", "nod_hat_telv_rm_headwear_12", "nod_r0_netch_leather_pauldron_l", "nod_r0_netch_leather_pauldron_r",
      		"nod_hat_straw_vd_helmclosed", "nod_hat_crab_vd_mudcrabhat", "nod_hat_straw_vd_helm_cloth", "nod_hat_crab_vd_03cloth_googles",
      		"nod_hat_netch_vd_boil_helm_open", "nod_hat_ash_ah_gogglehood_br", "nod_hat_crab_vd_mcrabhelmgoggle", "nod_hat_netch_vd_moragtong_mask",
      		"nod_retex_2pl_mvest_1", "nod_retex_2pl_mvest_1_dk", "nod_retex_2pl_mvest_1_k", "nod_as_goth3_hat_01",
      		"nod_as_goth3_hat_02", "nod_as_goth3_hat_03", "nod_as_goth3_hat_04", "nod_as_goth3_hat_05",
      		"nod_as_goth3_hat_06", "nod_as_goth3_hat_07", "nod_as_goth3_hat_10", "nod_as_goth3_hat_11",
      		"nod_as_goth3_hat_12", "nod_as_goth4_velvcoat1_r", "nod_as_goth4_velvcoat2_bl", "nod_as_goth4_velvcoat3_p",
      		"nod_as_goth4_velvcoat4_g", "nod_as_goth4_velvcoat5_bk", "nod_as_goth4_broccoat1_p", "nod_as_goth4_broccoat2_r",
      		"nod_as_goth4_broccoat3_g", "nod_as_goth4_broccoat4_bl", "nod_as_goth4_broccoat5_bk", "nod_as_goth4_webscoat",
      		"nod_as_goth4_workboot_1_bk", "nod_as_goth4_workboot_2_br", "nod_rv_necromask_nolens", "_rv_antlers_1",
      		"_rv_antlers_2", "_rv_horns_1", "_rv_horns_2", "_rv_horns_3",
      		"_rv_ears_1", "_rv_ears_2", "_rv_glasses1", "_rv_glasses2",
      		"_rv_glasses3", "_rv_glasses4", "_rv_goggles1", "_rv_goggles2",
      		"_rv_goggles3", "_rv_goggles4", "_rv_glasses4s", "_rv_glasses2s",
      		"_rv_glasses1s", "_rv_goggles5", "_rv_goggles6", "_rv_goggles7",
      		"_rv_goggles8", "_rv_lenses1", "_rv_blindfold1", "_rv_eyepatch1l",
      		"_rv_lenses2", "_rv_eyepatch1r", "_rv_facewrap_1", "_rv_facewrap_2",
      		"_rv_facewrap_3", "_rv_facewrap_4", "_rv_facewrap_5", "_rv_facewrap_6",
      		"_rv_facewrap_7", "_rv_facewrap_8", "_rv_ashmask_1", "_rv_ashmask_2",
      		"_rv_ashmask_3", "_rv_daedramask_1", "_rv_daedramask_2", "_rv_daedramask_3",
      		"_rv_orcishmask_1", "_rv_daedramask_4", "_rv_orcishmask_2", "nod_adnetch pauldron left",
      		"nod_adnetch boots", "nod_adnetch gauntlet left", "nod_adnetch gauntlet right", "nod_adnetch cuirass",
      		"nod_adnetch greaves", "nod_adnetch pauldron right", "nod_adnetch cuirass_ii", "nod_adnetch cuirass_iii",
      		"nod_adnetch coat", "nod_adnetch glove left", "nod_adnetch glove right", "nod_adnetch pauldron left ii",
      		"nod_adnetch pauldron right ii", "nod_adnetch beast boots", "nod_adnetch shield", "nod_bka2_femcoat_k07",
      		"nod_bka2_femcoat_k08", "nod_bka2_thief_armor2", "nod_retex_bka2_coat_of_arm1", "nod_retex_bka2_coat_of_arm2",
      		"nod_bka2_femcoat_k09", "ko_eye_patch_armor", "nod_ko_professional_curiass", "nod_ko_professional_boots_arm",
      		"aatl_art_targe_blooded", "aatl_a_buck_chitin", "aatl_a_buck_chitin_h", "aatl_a_buck_glass",
      		"aatl_a_buck_glass_h", "aatl_a_buck_netch_h", "aatl_a_ancient_shroud_chest", "aatl_a_ancient_shroud_gauntl",
      		"aatl_a_ancient_shroud_gauntr", "aatl_a_ancient_shroud_greaves", "aatl_a_ancient_shroud_paull", "aatl_a_ancient_shroud_paulr",
      		"aatl_a_ancient_shroud_helm", "aatl_a_ancient_shroud_boots", "aatl_a_buck_chitin_en1", "aatl_a_buck_chitin_en2",
      		"aatl_a_buck_chitin_h_en1", "aatl_a_buck_glass_h_en1", "aatl_a_buck_glass_en1", "aatl_a_buck_netch_h_en1",
      		"aatl_art_buck_manarend",
	},
	bonuses = {
		min = {
			{ effect = "fortifyFatigue", magnitude = 12 },
			{ effect = "fortifyAttribute", attribute = "agility", magnitude = 3 },
		},
		mid = {
			{ effect = "fortifyFatigue", magnitude = 20 },
			{ effect = "fortifyAttribute", attribute = "agility", magnitude = 5 },
			{ effect = "sanctuary", magnitude = 7 },
		},
		max = {
			{ effect = "fortifyFatigue", magnitude = 28 },
			{ effect = "fortifyAttribute", attribute = "agility", magnitude = 8 },
			{ effect = "sanctuary", magnitude = 10 },
			{ effect = "fortifySkill", skill = "acrobatics", magnitude = 12 },
		},
	},
}
