return {
        name = "Medium Armor",
        items = {
		"indoril shield", "indoril pauldron left", "indoril pauldron right", "indoril helmet",
      		"indoril cuirass", "indoril left gauntlet", "indoril right gauntlet", "indoril boots",
      		"imperial_chain_coif_helm", "imperial_chain_cuirass", "nordic_ringmail_cuirass", "bonemold_gah-julan_helm",
      		"bonemold_chuzei_helm", "bonemold_armun-an_helm", "bonemold_gah-julan_pauldron_r", "bonemold_armun-an_pauldron_r",
      		"bonemold_gah-julan_pauldron_l", "bonemold_armun-an_pauldron_l", "bonemold_gah-julan_cuirass", "bonemold_armun-an_cuirass",
      		"bonemold_bracer_left", "bonemold_bracer_right", "bonemold_greaves", "bonemold_boots",
      		"bonemold_shield", "bonemold_towershield", "dragonscale_helm", "dragonscale_cuirass",
      		"dragonscale_towershield", "orcish_helm", "orcish_pauldron_right", "orcish_pauldron_left",
      		"orcish_cuirass", "orcish_bracer_left", "orcish_greaves", "orcish_boots",
      		"orcish_towershield", "dreugh_helm", "dreugh_cuirass", "dreugh_shield",
      		"redoran_master_helm", "orcish_bracer_right", "imperial_chain_greaves", "bonemold_tshield_hlaaluguard",
      		"bonemold_tshield_redoranguard", "bonemold_tshield_telvanniguard", "bonemold_founders_helm", "holy_shield",
      		"storm helm", "heart wall", "succour of indoril", "lbonemold brace of horny fist",
      		"rbonemold bracer of horny fist", "helm of holy fire", "spirit of indoril", "bonemold_tshield_hrlb",
      		"bonemold_gah-julan_hhda", "bonemold_helm", "bonemold_pauldron_r", "bonemold_pauldron_l",
      		"bonemold_cuirass", "dreugh_cuirass_ttrm", "ebon_plate_cuirass_unique", "erur_dan_cuirass_unique",
      		"mountain spirit", "gondolier_helm", "ebon_plate_cuirass_unique_x", "helsethguard_helmet",
      		"helsethguard_boots", "helsethguard_cuirass", "helsethguard_greaves", "helsethguard_gauntlet_left",
      		"helsethguard_gauntlet_right", "helsethguard_pauldron_left", "helsethguard_pauldron_right", "adamantium boots",
      		"adamantium_bracer_left", "adamantium_bracer_right", "adamantium_cuirass", "adamantium_greaves",
      		"adamantium_pauldron_right", "adamantium_pauldron_left", "addamantium_helm", "adamantium_helm",
      		"bm bear boots", "bm bear cuirass", "bm bear left gauntlet", "bm bear right gauntlet",
      		"bm bear greaves", "bm bear helmet", "bm bear right pauldron", "bm bear left pauldron",
      		"bm_bear_boots_snow", "bm_bear_cuirass_snow", "bm_bear_greaves_snow", "bm_bear_helmet_snow",
      		"bm_bear_left_gauntlet_snow", "bm_bear_left_pauldron_snow", "bm_bear_right_gauntlet_snow", "bm_bear_right_pauldron_snow",
      		"bm bear helmet eddard", "bm_ice_boots", "bm_ice_cuirass", "bm_ice_gauntletl",
      		"bm_ice_gauntletr", "bm_ice_greaves", "bm_ice_helmet", "bm_ice_pauldronl",
      		"bm_ice_pauldronr", "bm bear helmet_ber", "bm_ice_shield", "bm bear shield",
      		"t_aka_regular_shield_01", "t_arg_hist_cuirass_01", "t_arg_hist_cuirass_freedom", "t_arg_hist_cuirass_visitor",
      		"t_bre_mithril_boots_01", "t_bre_mithril_cuirass_01", "t_bre_mithril_gauntlet_l_01", "t_bre_mithril_gauntlet_r_01",
      		"t_bre_mithril_greaves_01", "t_bre_mithril_helm_01", "t_bre_mithril_helm_02", "t_bre_mithril_pauldron_l_01",
      		"t_bre_mithril_pauldron_r_01", "t_bre_mithril_shield_01", "t_com_adamant_helm_01", "t_com_adamant_shield_01",
      		"t_com_adamant_towershield_01", "t_com_chain_cuirass_01", "t_com_chain_cuirass_02", "t_com_chain_cuirass_03",
      		"t_dae_gold_boots_01", "t_dae_gold_cuirass_01", "t_dae_gold_gauntletl_01", "t_dae_gold_gauntletr_01",
      		"t_dae_gold_greaves_01", "t_dae_gold_helm_01", "t_dae_gold_pauldronl_01", "t_dae_gold_pauldronr_01",
      		"t_dae_uni_bootsofatronach", "t_dae_uni_polyhedrascope_01", "t_de_bonemoldhearthguardboots", "t_de_bonemoldhearthguardcuirass",
      		"t_de_bonemoldhearthguardg_l", "t_de_bonemoldhearthguardg_r", "t_de_bonemoldhearthguardgreaves", "t_de_bonemoldhearthguardhelm",
      		"t_de_bonemoldhearthguardp_l", "t_de_bonemoldhearthguardp_r", "t_de_bonemoldkrage_boots_01", "t_de_bonemoldkrage_cuirass_01",
      		"t_de_bonemoldkrage_gauntletl_01", "t_de_bonemoldkrage_gauntletr_01", "t_de_bonemoldkrage_greaves_01", "t_de_bonemoldkrage_helm_01",
      		"t_de_bonemoldkrage_pauldronl_01", "t_de_bonemoldkrage_pauldronr_01", "t_de_bonemoldkragen_helm_01", "t_de_bonemoldmarad_cuirass_01",
      		"t_de_bonemoldmarad_cuirass_fire", "t_de_bonemoldmarad_helm_01", "t_de_bonemoldmarad_helm_02", "t_de_bonemoldmarad_helm_frost",
      		"t_de_bonemoldmarad_pauldronl_01", "t_de_bonemoldmarad_pauldronr_01", "t_de_bonemoldmarad_shield_01", "t_de_bonemoldmarad_shield_fire",
      		"t_de_bonemoldsacred_boots_01", "t_de_bonemoldsacred_cuirass_01", "t_de_bonemoldsacred_gauntl_01", "t_de_bonemoldsacred_gauntr_01",
      		"t_de_bonemoldsacred_helm_01", "t_de_bonemoldsacred_pauldl_01", "t_de_bonemoldsacred_pauldr_01", "t_de_bonemoldsammas_helm_01",
      		"t_de_bonemold_bracerl_longblade", "t_de_bonemold_bracerr_longblade", "t_de_bonemold_chuzei_boots", "t_de_bonemold_chuzei_boots_e",
      		"t_de_bonemold_chuzei_bracerl", "t_de_bonemold_chuzei_bracerl_e", "t_de_bonemold_chuzei_bracerr", "t_de_bonemold_chuzei_bracerr_e",
      		"t_de_bonemold_chuzei_cuirass", "t_de_bonemold_chuzei_cuirass_e", "t_de_bonemold_chuzei_greaves", "t_de_bonemold_chuzei_greaves_e",
      		"t_de_bonemold_chuzei_helm_e", "t_de_bonemold_chuzei_helm_fshld", "t_de_bonemold_chuzei_pauldl", "t_de_bonemold_chuzei_pauldl_e",
      		"t_de_bonemold_chuzei_pauldr", "t_de_bonemold_chuzei_pauldr_e", "t_de_bonemold_cuirass_seryn", "t_de_bonemold_cuirass_spite",
      		"t_de_bonemold_cuirass_stonewall", "t_de_bonemold_dagoth_shield_01", "t_de_bonemold_helmopen_01", "t_de_bonemold_helmrider_01",
      		"t_de_bonemold_indoril_shield_01", "t_de_bonemold_mora_boots_01", "t_de_bonemold_mora_brcrl_01", "t_de_bonemold_mora_brcrr_01",
      		"t_de_bonemold_mora_cuir_01", "t_de_bonemold_mora_greaves_01", "t_de_bonemold_mora_helm_01", "t_de_bonemold_mora_pauldl_01",
      		"t_de_bonemold_mora_pauldr_01", "t_de_bonemold_orethan_boots_01", "t_de_bonemold_orethan_brcrl_01", "t_de_bonemold_orethan_brcrr_01",
      		"t_de_bonemold_orethan_cuir_01", "t_de_bonemold_orethan_grvs_01", "t_de_bonemold_orethan_helm_01", "t_de_bonemold_orethan_pauldl_01",
      		"t_de_bonemold_orethan_pauldr_01", "t_de_bonemold_shield_skeleton", "t_de_bonemold_stone_boots", "t_de_bonemold_stone_cuirass",
      		"t_de_bonemold_stone_gauntletl", "t_de_bonemold_stone_gauntletr", "t_de_bonemold_stone_greaves", "t_de_bonemold_stone_helm",
      		"t_de_bonemold_stone_pauldl", "t_de_bonemold_stone_pauldr", "t_de_bonemold_tshield_gbonewalk", "t_de_bonemold_ulvra_boots",
      		"t_de_bonemold_ulvra_bracerl", "t_de_bonemold_ulvra_bracerr", "t_de_bonemold_ulvra_cuirass", "t_de_bonemold_ulvra_greaves",
      		"t_de_bonemold_ulvra_helm", "t_de_bonemold_ulvra_pauldl", "t_de_bonemold_ulvra_pauldr", "t_de_bonemold_water_boots",
      		"t_de_bonemold_water_boots_swim", "t_de_bonemold_water_bracerl", "t_de_bonemold_water_bracerr", "t_de_bonemold_water_cuirass",
      		"t_de_bonemold_water_greaves", "t_de_bonemold_water_helm", "t_de_bonemold_water_pauldl", "t_de_bonemold_water_pauldr",
      		"t_de_canyonwatch_boots_01", "t_de_canyonwatch_boots_jump", "t_de_canyonwatch_bracerl_01", "t_de_canyonwatch_bracerr_01",
      		"t_de_canyonwatch_celerity", "t_de_canyonwatch_cuirass_01", "t_de_canyonwatch_greaves_01", "t_de_canyonwatch_helm_01",
      		"t_de_canyonwatch_helm_attack", "t_de_canyonwatch_pauldronl_01", "t_de_canyonwatch_pauldronr_01", "t_de_dresbonemold_boots_01",
      		"t_de_dresbonemold_cuirass_01", "t_de_dresbonemold_gauntletl_01", "t_de_dresbonemold_gauntletr_01", "t_de_dresbonemold_greaves_01",
      		"t_de_dresbonemold_helm_01", "t_de_dresbonemold_pauldronl_01", "t_de_dresbonemold_pauldronr_01", "t_de_dresbonemold_shieldtow_01",
      		"t_de_dreugh_boots_01", "t_de_dreugh_bracerl_01", "t_de_dreugh_bracerr_01", "t_de_dreugh_greaves_01",
      		"t_de_dreugh_helm_closed", "t_de_dreugh_hunter_helm_01", "t_de_dreugh_hunter_helm_02", "t_de_dreugh_pauldronl_01",
      		"t_de_dreugh_pauldronl_swim", "t_de_dreugh_pauldronr_01", "t_de_dreugh_pauldronr_swim", "t_de_dreugh_shield_swim",
      		"t_de_guarskin_boots_01", "t_de_guarskin_bracerl_01", "t_de_guarskin_bracerl_spear", "t_de_guarskin_bracerr_01",
      		"t_de_guarskin_bracerr_spear", "t_de_guarskin_cuirass_01", "t_de_guarskin_greaves_01", "t_de_guarskin_helm_01",
      		"t_de_guarskin_helm_02", "t_de_guarskin_helm_03", "t_de_guarskin_helm_feather", "t_de_guarskin_pauldronl_01",
      		"t_de_guarskin_pauldronr_01", "t_de_guarskin_shield_01", "t_de_guarskin_shield_damfatigue", "t_de_indbonemold_boots_01",
      		"t_de_indbonemold_cuirass_01", "t_de_indbonemold_gauntletl_01", "t_de_indbonemold_gauntletr_01", "t_de_indbonemold_greaves_01",
      		"t_de_indbonemold_helmsaviour_01", "t_de_indbonemold_pauldronl_01", "t_de_indbonemold_pauldronl_02", "t_de_indbonemold_pauldronr_01",
      		"t_de_indbonemold_pauldronr_02", "t_de_indbonemold_shield_01", "t_de_indbonemold_shield_02", "t_de_indbonemold_shield_03",
      		"t_de_indbonemold_shield_04", "t_de_indbonemold_shield_05", "t_de_narsiswatch_boots_01", "t_de_narsiswatch_cuirass_01",
      		"t_de_narsiswatch_gauntletl_01", "t_de_narsiswatch_gauntletr_01", "t_de_narsiswatch_greaves01", "t_de_narsiswatch_helm_01",
      		"t_de_narsiswatch_pauldronl_01", "t_de_narsiswatch_pauldronr_01", "t_de_nativeebony_boots_01", "t_de_nativeebony_cuirass_01",
      		"t_de_nativeebony_gauntletl_01", "t_de_nativeebony_gauntletr_01", "t_de_nativeebony_greaves_01", "t_de_nativeebony_helmclosed_01",
      		"t_de_nativeebony_helmclosed_02", "t_de_nativeebony_helmopen_01", "t_de_nativeebony_helmopen_02", "t_de_nativeebony_pauldronl_01",
      		"t_de_nativeebony_pauldronr_01", "t_de_necrom_boots_01", "t_de_necrom_cuirass_01", "t_de_necrom_cuirass_02",
      		"t_de_necrom_gauntletl_01", "t_de_necrom_gauntletr_01", "t_de_necrom_greaves_01", "t_de_necrom_helm_01",
      		"t_de_necrom_pauldronl_01", "t_de_necrom_pauldronr_01", "t_de_necrom_shield_01", "t_de_ordinator_greaves_01",
      		"t_de_redbonemold_helmopen_01", "t_de_redherobonemold_cuirass_01", "t_de_redherobonemold_helm_01", "t_de_redherobonemold_helm_02",
      		"t_de_redherobonemold_helm_03", "t_de_redherobonemold_pauldrl_01", "t_de_redherobonemold_pauldrr_01", "t_de_redmastbonemold_cuirass_01",
      		"t_de_redmastbonemold_pauldrl_01", "t_de_redmastbonemold_pauldrr_01", "t_de_riverwatch_boots_01", "t_de_riverwatch_boots_waterwalk",
      		"t_de_riverwatch_cuirass_01", "t_de_riverwatch_gauntl_01", "t_de_riverwatch_gauntr_01", "t_de_riverwatch_greaves_01",
      		"t_de_riverwatch_helm_01", "t_de_riverwatch_pauldronl_01", "t_de_riverwatch_pauldronr_01", "t_de_thirrbonemold_boots_01",
      		"t_de_thirrbonemold_bracer_01_l", "t_de_thirrbonemold_bracer_01_r", "t_de_thirrbonemold_cuirass_01", "t_de_thirrbonemold_greaves_01",
      		"t_de_thirrbonemold_helm_01", "t_de_thirrbonemold_pauldrn_01_l", "t_de_thirrbonemold_pauldrn_01_r", "t_de_uni_dreugh_tyrant_helm",
      		"t_de_uni_facelesshelm", "t_de_uni_irfeidsshoulderl", "t_de_uni_irfeidsshoulderr", "t_de_uni_shoulderofghostlightl",
      		"t_de_uni_shoulderofghostlightr", "t_de_uni_vanguard", "t_de_uni_vivecshield", "t_de_uni_wraithmail_01",
      		"t_dwe_gold_helmopen", "t_dwe_scrap_bracer_l", "t_dwe_scrap_bracer_r", "t_dwe_scrap_pauldron_l",
      		"t_dwe_scrap_pauldron_r", "t_dwe_scrap_boots", "t_dwe_scrap_cuirass", "t_dwe_scrap_greaves",
      		"t_dwe_scrap_helmet", "t_glb_var_decapitationhelm", "t_imp_chain_boots_01", "t_imp_chain_gauntletl_01",
      		"t_imp_chain_gauntletr_02", "t_imp_chainmail_helm_01", "t_imp_chainmail_helm_02", "t_imp_chainmail_helm_03",
      		"t_imp_chainmail_helm_04", "t_imp_chainmail_cuirass_01", "t_imp_chainmail_cuirass_02", "t_imp_chainmail_cuirass_03",
      		"t_imp_chainmail_cuirass_04", "t_imp_colbronzeold_helm_01", "t_imp_coliron2_boots_01", "t_imp_coliron2_bracerl_01",
      		"t_imp_coliron2_bracerr_01", "t_imp_coliron2_cuirass_01", "t_imp_coliron2_greaves_01", "t_imp_coliron2_helm_01",
      		"t_imp_coliron2_pauldronl_01", "t_imp_coliron2_pauldronr_01", "t_imp_collamellar_boots_01", "t_imp_collamellar_bracerl_01",
      		"t_imp_collamellar_bracerr_01", "t_imp_collamellar_cuirass_01", "t_imp_collamellar_greaves_01", "t_imp_collamellar_helmopen_01",
      		"t_imp_collamellar_helm_01", "t_imp_collamellar_maskhelm_01", "t_imp_collamellar_maskhelm_02", "t_imp_collamellar_pauldronl_01",
      		"t_imp_collamellar_pauldronr_01", "t_imp_dragonscale_barcerl_01", "t_imp_dragonscale_barcerr_01", "t_imp_dragonscale_boots_01",
      		"t_imp_dragonscale_bracerl_01", "t_imp_dragonscale_bracerl_heal", "t_imp_dragonscale_bracerr_01", "t_imp_dragonscale_bracerr_heal",
      		"t_imp_dragonscale_greaves_01", "t_imp_dragonscale_pauldronl_01", "t_imp_dragonscale_pauldronr_01", "t_imp_dragonscale_cuirass_01",
      		"t_imp_dragonscale_helm_01", "t_imp_gold_cuirass_01", "t_imp_gold_helm_01", "t_imp_gold_pauldronl_01",
      		"t_imp_gold_pauldronr_01", "t_imp_gold_shieldbuckler_01", "t_imp_gold_shieldbuckler_luck", "t_imp_guardsutch_cuirass_01",
      		"t_imp_guardsutch_gauntletl_01", "t_imp_guardsutch_gauntletr_01", "t_imp_guardsutch_helm_01", "t_imp_guardsutch_pauldrl_01",
      		"t_imp_guardsutch_pauldrr_01", "t_imp_guardsutch_shieldtow_01", "t_imp_guardtown1_cuirass_01", "t_imp_guardtown1_gauntletl_01",
      		"t_imp_guardtown1_gauntletr_01", "t_imp_guardtown1_greaves_01", "t_imp_guardtown1_pauldrl_01", "t_imp_guardtown1_pauldrr_01",
      		"t_imp_guardtown1_shieldanv_01", "t_imp_guardtown2_boots_01", "t_imp_guardtown2_cuirass_01", "t_imp_guardtown2_gauntletl_01",
      		"t_imp_guardtown2_gauntletr_01", "t_imp_guardtown2_greaves_01", "t_imp_guardtown2_pauldrl_01", "t_imp_guardtown2_pauldrr_01",
      		"t_imp_guardtown3_cuirass_01", "t_imp_guardtown3_pauldrl_01", "t_imp_guardtown3_pauldrr_01", "t_imp_mananaut_boots_01",
      		"t_imp_mananaut_cuirass_01", "t_imp_mananaut_gauntl_01", "t_imp_mananaut_gauntr_01", "t_imp_mananaut_helm_01",
      		"t_imp_mananaut_helm_02", "t_imp_militia_cuirass_01", "t_imp_militia_gauntl_01", "t_imp_militia_gauntr_01",
      		"t_imp_oathbound_shield_01", "t_imp_reman_boots_01", "t_imp_reman_bracerl_01", "t_imp_reman_bracerr_01",
      		"t_imp_reman_cuirass_01", "t_imp_reman_greaves_01", "t_imp_reman_helm_01", "t_imp_reman_pauldronl_01",
      		"t_imp_reman_pauldronr_01", "t_imp_reman_shield_01", "t_imp_uni_benduolohelm", "t_imp_uni_wardofakavir",
      		"t_imp_uni_nafaalilargusscales", "t_mao_scale_boots_01", "t_mao_scale_bracer_l_01", "t_mao_scale_bracer_r_01",
      		"t_mao_scale_cuirass_01", "t_mao_scale_greaves_01", "t_mao_scale_helm_01", "t_mao_scale_pauld_l_01",
      		"t_mao_scale_pauld_r_01", "t_nor_companion_boots_01", "t_nor_companion_cuirass_01", "t_nor_companion_gauntletl_01",
      		"t_nor_companion_gauntletr_01", "t_nor_companion_greaves_01", "t_nor_companion_pauldronl_01", "t_nor_companion_pauldronr_01",
      		"t_nor_guardfalkr_boots_01", "t_nor_guardfalkr_bracerl_01", "t_nor_guardfalkr_bracerr_01", "t_nor_guardfalkr_cuirass_01",
      		"t_nor_guardfalkr_greaves_01", "t_nor_guardfalkr_helm_01", "t_nor_guardfalkr_helm_02", "t_nor_guardfalkr_pauldronl_01",
      		"t_nor_guardfalkr_pauldronr_01", "t_nor_guardfalkr_shield_01", "t_nor_guardfalkr_towershield_01", "t_nor_guardkarth_shield_01",
      		"t_nor_guard_boots_01", "t_nor_guard_cuirass_01", "t_nor_guard_gauntletl_01", "t_nor_guard_gauntletr_01",
      		"t_nor_guard_greaves_01", "t_nor_guard_helm_01", "t_nor_guard_pauldronl_01", "t_nor_guard_pauldronr_01",
      		"t_nor_ironwood_shield_01", "t_nor_ironwood_shield_02", "t_nor_ringmail_boots_01", "t_nor_ringmail_boots_02",
      		"t_nor_ringmail_bracerl_02", "t_nor_ringmail_bracerr_02", "t_nor_ringmail_cuirass_01", "t_nor_ringmail_cuirass_sbulwark",
      		"t_nor_ringmail_greaves_01", "t_nor_ringmail_greaves_02", "t_nor_ringmail_helm_closed", "t_nor_ringmail_helmet_01",
      		"t_nor_ringmail_helmet_02", "t_nor_ringmail_pauldronl_02", "t_nor_ringmail_pauldronr_02", "t_nor_sabrecat_helm_01",
      		"t_nor_sabrecat_helm_02", "t_nor_sabrecat_helm_sight", "t_nor_toadscale_boots_01", "t_nor_toadscale_boots_02",
      		"t_nor_toadscale_cuirass_01", "t_nor_toadscale_cuirass_02", "t_nor_toadscale_gauntletl_01", "t_nor_toadscale_gauntletl_02",
      		"t_nor_toadscale_gauntletr_01", "t_nor_toadscale_gauntletr_02", "t_nor_toadscale_greaves_01", "t_nor_toadscale_greaves_02",
      		"t_nor_toadscale_helm_01", "t_nor_toadscale_helm_02", "t_nor_toadscale_helm_03", "t_nor_toadscale_helm_04",
      		"t_nor_toadscale_pauldl_01", "t_nor_toadscale_pauldl_02", "t_nor_toadscale_pauldr_01", "t_nor_toadscale_pauldr_02",
      		"t_nor_toadscale_shield_01", "t_nor_toadscale_shield_02", "t_nor_uni_dcultmask_01", "t_nor_uni_snowdrakepelt",
      		"t_nor_wood_shield_01", "t_nor_wood_shield_02", "t_nor_wood_shield_03", "t_orc_regular_helmopen_01",
      		"t_qc_shellmold_boots_01", "t_qc_shellmold_bracerl_01", "t_qc_shellmold_bracerr_01", "t_qc_shellmold_cuirass_01",
      		"t_qc_shellmold_greaves_01", "t_qc_shellmold_helm_01", "t_qc_shellmold_pauldl_01", "t_qc_shellmold_pauldr_01",
      		"t_qyc_shellmold_boots_01", "t_qyc_shellmold_bracerl_01", "t_qyc_shellmold_bracerr_01", "t_qyc_shellmold_cuirass_01",
      		"t_qyc_shellmold_greaves_01", "t_qyc_shellmold_helm_01", "t_qyc_shellmold_pauldl_01", "t_qyc_shellmold_pauldr_01",
      		"t_rea_wormmouth_boots_01", "t_rea_wormmouth_bracerl_01", "t_rea_wormmouth_bracerr_01", "t_rea_wormmouth_cuirass_01",
      		"t_rea_wormmouth_greaves_01", "t_rea_wormmouth_helm_01", "t_rea_wormmouth_helm_poison", "t_rea_wormmouth_pauldronl_01",
      		"t_rea_wormmouth_pauldronr_01", "t_rga_alikr_buckler", "t_rga_crownguard1_boots_01", "t_rga_crownguard1_cuirass_01",
      		"t_rga_crownguard1_greaves_01", "t_rga_crownguard1_helm_01", "t_rga_crownguard1_pauldronl_01", "t_rga_crownguard1_pauldronr_01",
      		"t_we_wenbone_boots_01", "t_we_wenbone_bracerl_01", "t_we_wenbone_bracerr_01", "t_we_wenbone_cuirass_01",
      		"t_we_wenbone_greaves_01", "t_we_wenbone_helm_01", "t_we_wenbone_pauldronl_01", "t_we_wenbone_pauldronr_01",
      		"t_we_wenbone_shieldtow_01", "ab_a_bonemhelmopen", "ab_a_dreughboots", "ab_a_dreughbracerl",
      		"ab_a_dreughbracerr", "ab_a_dreughgreaves", "ab_a_dreughhelmclose", "ab_a_dreughpldleft",
      		"ab_a_dreughpldright", "ab_a_orchelmopen", "ab_a_steelboots", "ab_a_steelcuirass",
      		"ab_a_steelgntlleft", "ab_a_steelgntlright", "ab_a_steelgreaves", "ab_a_steelhelm",
      		"ab_a_steelpldrleft", "ab_a_steelpldrright", "nod_dnk_sarano_cuirass", "nod_dnk_virith_cuirass",
      		"nod_dnk_virith_p_left", "nod_dnk_virith_p_right", "nod_dnk_sixth_cuirass", "nod_dnk_hlaalu_cuirass",
      		"nod_dnk_sala_cuirass", "nod_dnk_sala_p_left", "nod_dnk_sala_p_right", "nod_dnk_dagoth_cuirass",
      		"nod_ardres", "nod_arhlaalu", "nod_arindoril", "nod_arindoril2",
      		"nod_arredoran", "nod_arspellsword", "nod_artelvanni", "nod_ar_indrobe1",
      		"nod_ar_indhelm", "nod_ar_indrobe_nc1", "nod_arindoril_hood", "nod_arindoril_hood&mask",
      		"nod_ar_indoril helmet2", "nod_ar_pauldron left", "nod_ar_pauldron right", "adnetch pauldron left",
      		"adnetch boots", "adnetch gauntlet left", "adnetch gauntlet right", "adnetch cuirass",
      		"adnetch greaves", "adnetch pauldron right", "adnetch cuirass_ii", "adnetch cuirass_iii",
      		"adnetch coat", "adnetch glove left", "adnetch glove right", "adnetch pauldron left ii",
      		"adnetch pauldron right ii", "adnetch beast boots", "adnetch shield", "nod_rv_adamantium boots",
      		"nod_rv_adamantium_cuirass", "nod_rv_adamantium_helmet", "nod_rv_adamantium_greaves", "nod_rv_adamantium_gauntlet_left",
      		"nod_rv_adamantium_gauntlet_r", "nod_rv_adamantium_pauldron_left", "nod_rv_adamantium_pauldron_r", "nod_rv_adamantium_robe_left",
      		"nod_rv_adamantium_robe_right", "nod_rv_adamantium_cuirass 2", "nod_rv_adamantium boots_red", "nod_rv_adamantium_cuirass_red",
      		"nod_rv_adamantium_cuirass 2_red", "nod_rv_adamantium_gntlet_left_r", "nod_rv_adamantium_gauntlet_r_r", "nod_rv_adamantium_helmet_red",
      		"nod_rv_adamantium_pauldron_l_rd", "nod_rv_adamantium_pauldron_r_r", "nod_rv_adamantium_robe_left_r", "nod_rv_adamantium_robe_right_r",
      		"nod_rv_dwemscr_boots", "nod_rv_dwemscr_bracer_left", "nod_rv_dwemscr_bracer_right", "nod_rv_dwemscr_cuirass",
      		"nod_rv_dwemscr_helmet", "nod_rv_dwemscr_greaves", "nod_rv_dwemscr_pauldron_left", "nod_rv_dwemscr_pauldron_right",
      		"nod_pb_neen-enamor_cuirass", "nod_pb_neen-enamor_pauldron_l", "nod_pb_neen-enamor_pauldron_r", "nod_pb_neen-enamor_helm_01",
      		"nod_pb_neen-enamor_helm_02", "nod_pb_neen-enamor_helm_03", "nod_pb_tshield_dagoth", "nod_pb_tshield_dagoth_g",
      		"nod_pb_neen-enamor_greaves", "nod_hat_bug_b", "nod_hat_crab_ah_crabhatmask", "nod_ah_woodenshield",
      		"nod_hat_ash_vd_gondaliergoggles", "nod_bka2_femcoat_k06", "nod_bka2_femcoat_k02", "nod_bka2_femcoat_k03",
      		"aatl_art_fearstruck", "aatl_a_buck_dwemer_h", "aatl_a_buck_iron", "aatl_a_buck_dwemer_h_en1",
      		"aatl_a_buck_iron_en1", "aatl_a_buck_iron_nord", "aatl_a_buck_iron_nord_en1",
	},
	bonuses = {
		min = {
			{ effect = "fortifyFatigue", magnitude = 12 },
			{ effect = "resistNormalWeapons", magnitude = 3 },
		},
		mid = {
			{ effect = "fortifyFatigue", magnitude = 20 },
			{ effect = "resistNormalWeapons", magnitude = 5 },
			{ effect = "fortifyHealth", magnitude = 12 },
		},
		max = {
			{ effect = "fortifyFatigue", magnitude = 28 },
			{ effect = "resistNormalWeapons", magnitude = 8 },
			{ effect = "fortifyHealth", magnitude = 18 },
			{ effect = "fortifyAttribute", attribute = "endurance", magnitude = 8 },
		},
	},
}
