-- =========================================================================
--  Set Bonus -- OAAB add-on (auto-generated)
--  Re-links OAAB armour to the base Set Bonus sets via the interop. Loads only
--  when OAAB items are present, so it is safe with or without OAAB installed.
-- =========================================================================

local setBonus = require("Static.SetBonus.interop")

local function present(id) return tes3.getObject(id) ~= nil end

local function registerOAAB()
    if not (setBonus and setBonus.version and setBonus.version >= 2) then return end

    if present("AB_a_CephHelmOpen") and setBonus.getSet("Cephalopod") then
        setBonus.addItems("Cephalopod", {
            "AB_a_CephHelmOpen", "AB_a_CephPauldronLeft", "AB_a_CephPauldronRight",
        })
    end
    if present("AB_a_ChitinHelmOpen") and setBonus.getSet("Chitin") then
        setBonus.addItems("Chitin", {
            "AB_a_ChitinHelmOpen", "AB_a_ChitinHlaHelm01", "AB_a_ChitinRedHelm01",
            "AB_a_ChitinScoutHelm", "AB_a_ChitinTelHelm01",
        })
    end
    if present("AB_a_ClothHelm1") and setBonus.getSet("Cloth") then
        setBonus.addItems("Cloth", {
            "AB_a_ClothHelm1", "AB_a_ClothHelm2", "AB_a_ClothHelm3",
        })
    end
    if present("AB_a_DaeAzuraHelm") and setBonus.getSet("Daedric") then
        setBonus.addItems("Daedric", {
            "AB_a_DaeAzuraHelm", "AB_a_DaeDagonHelm", "AB_a_DaeMolagHelm",
            "AB_a_DaeSheogHelm",
        })
    end
    if present("AB_a_DreughBoots") and setBonus.getSet("Dreugh") then
        setBonus.addItems("Dreugh", {
            "AB_a_DreughBoots", "AB_a_DreughBracerL", "AB_a_DreughBracerR",
            "AB_a_DreughGreaves", "AB_a_DreughHelmClose", "AB_a_DreughPldLeft",
            "AB_a_DreughPldRight",
        })
    end
    if present("AB_a_GlassAssassinPauldronLeft") and setBonus.getSet("Glass") then
        setBonus.addItems("Glass", {
            "AB_a_GlassAssassinPauldronLeft", "AB_a_GlassAssassinPauldronRight", "AB_a_GlassHelmClose",
        })
    end
    if present("AB_a_ChitinHlaHelm01") and setBonus.getSet("House Hlaalu") then
        setBonus.addItems("House Hlaalu", {
            "AB_a_ChitinHlaHelm01",
        })
    end
    if present("AB_a_IronDeBoots") and setBonus.getSet("Iron") then
        setBonus.addItems("Iron", {
            "AB_a_IronDeBoots", "AB_a_IronDeCuirass", "AB_a_IronDeHelm",
            "AB_a_IronDeHelmTong", "AB_a_IronDePldLeft", "AB_a_IronDePldRight",
        })
    end
    if present("AB_a_LeatherHat") and setBonus.getSet("Leather") then
        setBonus.addItems("Leather", {
            "AB_a_LeatherHat",
        })
    end
    if present("AB_a_MoragTongHelm01") and setBonus.getSet("Morag Tong") then
        setBonus.addItems("Morag Tong", {
            "AB_a_MoragTongHelm01", "AB_a_MoragTongHelm02", "AB_a_MoragTongHelm03",
            "AB_a_MoragTongHelm04",
        })
    end
    if present("AB_a_IronDeBoots") and setBonus.getSet("Native") then
        setBonus.addItems("Native", {
            "AB_a_IronDeBoots", "AB_a_IronDeCuirass", "AB_a_IronDeHelm",
            "AB_a_IronDeHelmTong", "AB_a_IronDePldLeft", "AB_a_IronDePldRight",
        })
    end
    if present("AB_a_NetchBoilPldLeft") and setBonus.getSet("Netch Leather") then
        setBonus.addItems("Netch Leather", {
            "AB_a_NetchBoilPldLeft", "AB_a_NetchBoilPldRight", "AB_a_NetchimanCap",
        })
    end
    if present("AB_a_OrcHelmOpen") and setBonus.getSet("Orcish") then
        setBonus.addItems("Orcish", {
            "AB_a_OrcHelmOpen",
        })
    end
    if present("AB_a_OrcHelmOpen") and setBonus.getSet("Orsimer") then
        setBonus.addItems("Orsimer", {
            "AB_a_OrcHelmOpen",
        })
    end
    if present("AB_a_SteelBoots") and setBonus.getSet("Steel") then
        setBonus.addItems("Steel", {
            "AB_a_SteelBoots", "AB_a_SteelCuirass", "AB_a_SteelGntlLeft",
            "AB_a_SteelGntlRight", "AB_a_SteelGreaves", "AB_a_SteelHelm",
            "AB_a_SteelHelmOpen", "AB_a_SteelPldrLeft", "AB_a_SteelPldrRight",
        })
    end
    if present("AB_a_CephHelmOpen") and setBonus.getSet("House Telvanni") then
        setBonus.addItems("House Telvanni", {
            "AB_a_CephHelmOpen", "AB_a_DustBoots", "AB_a_DustBracerLeft",
            "AB_a_DustBracerRight", "AB_a_DustChest", "AB_a_DustGreaves",
            "AB_a_DustHelm", "AB_a_DustPldrLeft", "AB_a_DustPldrRight",
        })
    end
    -- >>> SETBONUS CLASS ARMOR (auto-generated by gen_class_sets.py) >>>
    if setBonus.getSet("Heavy Armor") then
        setBonus.addItems("Heavy Armor", {
            "ab_a_daeazurahelm", "ab_a_daedagonhelm", "ab_a_daemolaghelm", "ab_a_daesheoghelm",
            "ab_a_ebonyhelmopen", "ab_a_impbmboots", "ab_a_impbmcuirass", "ab_a_impbmgreaves",
            "ab_a_impbmhelm", "ab_a_impbmpldleft", "ab_a_impbmpldright", "ab_a_invisshield",
            "ab_a_irondeboots", "ab_a_irondecuirass", "ab_a_irondehelm", "ab_a_irondehelmtong",
            "ab_a_irondepldleft", "ab_a_irondepldright", "ab_a_steelhelmopen",
        })
    end
    if setBonus.getSet("Medium Armor") then
        setBonus.addItems("Medium Armor", {
            "ab_a_bonemhelmopen", "ab_a_dreughboots", "ab_a_dreughbracerl", "ab_a_dreughbracerr",
            "ab_a_dreughgreaves", "ab_a_dreughhelmclose", "ab_a_dreughpldleft", "ab_a_dreughpldright",
            "ab_a_orchelmopen", "ab_a_steelboots", "ab_a_steelcuirass", "ab_a_steelgntlleft",
            "ab_a_steelgntlright", "ab_a_steelgreaves", "ab_a_steelhelm", "ab_a_steelpldrleft",
            "ab_a_steelpldrright",
        })
    end
    if setBonus.getSet("Light Armor") then
        setBonus.addItems("Light Armor", {
            "ab_a_backbasket", "ab_a_bonemlightboots", "ab_a_bonemlightbracerl", "ab_a_bonemlightbracerr",
            "ab_a_bonemlightcuirass", "ab_a_bonemlightgreaves", "ab_a_bonemlighthelm", "ab_a_bonemlightpaull",
            "ab_a_bonemlightpaulr", "ab_a_bugblueboots", "ab_a_bugbluecuirass", "ab_a_bugbluegntleft",
            "ab_a_bugbluegntright", "ab_a_bugbluegreaves", "ab_a_bugbluehelm", "ab_a_bugbluepldleft",
            "ab_a_bugbluepldright", "ab_a_bugblueshield", "ab_a_buggreenboots", "ab_a_buggreencuirass",
            "ab_a_buggreengntleft", "ab_a_buggreengntright", "ab_a_buggreengreaves", "ab_a_buggreenhelm",
            "ab_a_buggreenpldleft", "ab_a_buggreenpldright", "ab_a_buggreenshield", "ab_a_cephhelmopen",
            "ab_a_cephpauldronleft", "ab_a_cephpauldronright", "ab_a_chitinhelmopen", "ab_a_chitinhlahelm01",
            "ab_a_chitinredhelm01", "ab_a_chitinscouthelm", "ab_a_chitintelhelm01", "ab_a_clothhelm1",
            "ab_a_clothhelm2", "ab_a_clothhelm3", "ab_a_dustboots", "ab_a_dustbracerleft",
            "ab_a_dustbracerright", "ab_a_dustchest", "ab_a_dustgreaves", "ab_a_dusthelm",
            "ab_a_dustpldrleft", "ab_a_dustpldrright", "ab_a_eggminerhelm", "ab_a_glassassassinpauldronleft",
            "ab_a_glassassassinpauldronright", "ab_a_glasshelmclose", "ab_a_leatherhat", "ab_a_moragtonghelm01",
            "ab_a_moragtonghelm02", "ab_a_moragtonghelm03", "ab_a_moragtonghelm04", "ab_a_netchboilpldleft",
            "ab_a_netchboilpldright", "ab_a_netchimancap", "ab_a_wickerhelm", "ab_a_wickerhelm02",
            "ab_c_commonhood01", "ab_c_commonhood02", "ab_c_commonhood02h", "ab_c_commonhood02hh",
            "ab_c_commonhood02r", "ab_c_commonhood02rr", "ab_c_commonhood02t", "ab_c_commonhood02tt",
            "ab_c_commonhood03", "ab_c_commonhood03a", "ab_c_commonhood03b", "ab_c_commonhood04",
            "ab_c_commonhood05", "ab_c_commonhood05a", "ab_c_commonhood05b", "ab_c_commonhood05c",
            "ab_c_commonhoodblack", "ab_c_dwrvhat", "ab_c_expensivehood01", "ab_c_expensivehood02",
            "ab_c_expensivehood02a", "ab_c_expensivehood03", "ab_c_exquisitehood01", "ab_c_extravaganthood01",
            "ab_c_extravaganthood01a", "ab_c_extravaganthood01b", "ab_c_extravaganthood01c", "ab_c_extravaganthood01h",
            "ab_c_extravaganthood01r", "ab_c_extravaganthood01t", "ab_c_extravaganthood02",
        })
    end
    -- <<< SETBONUS CLASS ARMOR <<<
end

event.register(tes3.event.initialized, registerOAAB, { priority = -100 })
